<a href="https://colab.research.google.com/github/aoonging/BSC_DPDM2025/blob/main/Midterm_663020036_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  1.Import Data

In [48]:
import pandas as pd

In [49]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [50]:
os.listdir('/content/drive/MyDrive/BSC DPDM midterm 2025')

['Daily rain - (Statistics 2012-2024)',
 'Output - (Clean monthly rain - 2025)',
 'Input - (Operation Daily rain from API_ 2025)']

In [62]:
stations = pd.read_csv('/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
stations

       Node        Lat        Long
0      ACRU  15.788054  104.642235
1      BBHN   9.536913   98.579490
2      BBUA  17.372976  103.984436
3      BCNG  17.386840  103.290870
4      BDAR  14.587073  102.495190
..      ...        ...         ...
380  YOM003  18.265924  100.177060
381  YOM008  16.708166  100.171780
382  YOM009  16.310750  100.271750
383  YOM010  18.133717  100.124596
384  YOM012  17.021260   99.819710

[385 rows x 3 columns]

In [52]:
import os
import pandas as pd

dfs = []
root_directory = '/content/drive/MyDrive/BSC DPDM midterm 2025'

for dirpath, dirnames, filenames in os.walk(root_directory):
    for filename in filenames:
        if filename.endswith('.csv'):
            file_path = os.path.join(dirpath, filename)
            try:
                df = pd.read_csv(file_path)

                print('📂 Folder:', os.path.basename(dirpath))
                print('📄 File:', filename)
                print('🔹 Shape:', df.shape)
                print('🔹 Columns:', df.columns.tolist())
                print('🔹 Data types:')
                print(df.dtypes)
                print('🔹 Head:')
                display(df.head())
                print('-' * 80)

                df['source_folder'] = os.path.basename(dirpath)
                df['source_file'] = filename
                dfs.append(df)

            except Exception as e:
                print(f"Error reading {file_path}: {e}")

📂 Folder: Daily rain - (Statistics 2012-2024)
📄 File: hii_daily_rain.csv
🔹 Shape: (3768463, 13)
🔹 Columns: ['station_code', 'measure_datetime', 'data', 'station_name', 'latitude', 'longitude', 'quality_flag', 'basin', 'sub_basin', 'tambon', 'amphoe', 'province', 'data_type']
🔹 Data types:
station_code         object
measure_datetime     object
data                float64
station_name         object
latitude            float64
longitude           float64
quality_flag         object
basin                object
sub_basin            object
tambon               object
amphoe               object
province             object
data_type            object
dtype: object
🔹 Head:

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

--------------------------------------------------------------------------------
📂 Folder: Output - (Clean monthly rain - 2025)
📄 File: Y_monthly_rain_HII_operation.csv
🔹 Shape: (18, 4)
🔹 Columns: ['Node', 'rain', 'month', 'year']
🔹 Data types:
Node      object
rain     float64
month      int64
year       int64
dtype: object
🔹 Head:

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

--------------------------------------------------------------------------------
📂 Folder: Input - (Operation Daily rain from API_ 2025)
📄 File: Stations in the model_HII.csv
🔹 Shape: (385, 3)
🔹 Columns: ['Node', 'Lat', 'Long']
🔹 Data types:
Node     object
Lat     float64
Long    float64
dtype: object
🔹 Head:

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-02.csv
🔹 Shape: (889, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,575571,BKC007,2025-08-02
1,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,1512928,NaN,2025-08-02
2,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,1512927,NaN,2025-08-02
3,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,9.0,1395256,NaN,2025-08-02
4,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,1395255,NaN,2025-08-02

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-04.csv
🔹 Shape: (889, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-05 00:00:00+07:00,2025-08-05T07:00:00+07:00,0.0,488,CHHA,2025-08-04
1,2025-08-05 00:00:00+07:00,2025-08-05T07:00:00+07:00,0.0,168,THNM,2025-08-04
2,2025-08-05 00:00:00+07:00,2025-08-05T07:00:00+07:00,0.0,335,KON004,2025-08-04
3,2025-08-05 00:00:00+07:00,2025-08-05T07:00:00+07:00,0.0,411,VLGE25,2025-08-04
4,2025-08-05 00:00:00+07:00,2025-08-05T07:00:00+07:00,0.4,242,VLGE08,2025-08-04

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-03.csv
🔹 Shape: (889, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-04 00:00:00+07:00,2025-08-04T07:00:00+07:00,0.0,722,POCG,2025-08-03
1,2025-08-04 00:00:00+07:00,2025-08-04T07:00:00+07:00,0.0,941,VLGE06,2025-08-03
2,2025-08-04 00:00:00+07:00,2025-08-04T07:00:00+07:00,25.8,923,STH019,2025-08-03
3,2025-08-04 00:00:00+07:00,2025-08-04T07:00:00+07:00,1.0,13886,SWR019,2025-08-03
4,2025-08-04 00:00:00+07:00,2025-08-04T07:00:00+07:00,0.0,511,WGSA,2025-08-03

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-01.csv
🔹 Shape: (891, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-02 00:00:00+07:00,2025-08-02T07:00:00+07:00,0.0,493,YOM004,2025-08-01
1,2025-08-02 00:00:00+07:00,2025-08-02T07:00:00+07:00,0.0,495,VLGE36,2025-08-01
2,2025-08-02 00:00:00+07:00,2025-08-02T07:00:00+07:00,0.2,496,SNGT,2025-08-01
3,2025-08-02 00:00:00+07:00,2025-08-02T07:00:00+07:00,0.0,497,WCHN,2025-08-01
4,2025-08-02 00:00:00+07:00,2025-08-02T07:00:00+07:00,0.0,498,NMKI,2025-08-01

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-27.csv
🔹 Shape: (896, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-28 00:00:00+07:00,2025-08-28T07:00:00+07:00,7.0,1373689,NaN,2025-08-27
1,2025-08-28 00:00:00+07:00,2025-08-28T07:00:00+07:00,0.0,1109580,ONE091,2025-08-27
2,2025-08-28 00:00:00+07:00,2025-08-28T07:00:00+07:00,3.6,695,LMKO,2025-08-27
3,2025-08-28 00:00:00+07:00,2025-08-28T07:00:00+07:00,0.0,1198762,YOM016,2025-08-27
4,2025-08-28 00:00:00+07:00,2025-08-28T07:00:00+07:00,1.2,13878,SWR011,2025-08-27

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-07.csv
🔹 Shape: (888, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-08 00:00:00+07:00,2025-08-08T07:00:00+07:00,0.0,574,NGBA,2025-08-07
1,2025-08-08 00:00:00+07:00,2025-08-08T07:00:00+07:00,13.2,703,NMNO,2025-08-07
2,2025-08-08 00:00:00+07:00,2025-08-08T07:00:00+07:00,13.4,175,NYK008,2025-08-07
3,2025-08-08 00:00:00+07:00,2025-08-08T07:00:00+07:00,1.4,187,NYK001,2025-08-07
4,2025-08-08 00:00:00+07:00,2025-08-08T07:00:00+07:00,0.0,64,NMKH,2025-08-07

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: rain_hii_20250831.csv
🔹 Shape: (1268, 3)
🔹 Columns: ['station_code', 'measure_datetime', 'value']
🔹 Data types:
station_code         object
measure_datetime     object
value               float64
dtype: object
🔹 Head:

  station_code measure_datetime  value
0         ACRU        8/31/2025    0.2
1       AIT001        8/31/2025    0.0
2       AIT002        8/31/2025    0.2
3       AIT005        8/31/2025    0.2
4       AIT008        8/31/2025    2.6

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-19.csv
🔹 Shape: (887, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-20 00:00:00+07:00,2025-08-20T07:00:00+07:00,0.2,482,NAN004,2025-08-19
1,2025-08-20 00:00:00+07:00,2025-08-20T07:00:00+07:00,0.0,481,PICI,2025-08-19
2,2025-08-20 00:00:00+07:00,2025-08-20T07:00:00+07:00,0.0,478,NAN010,2025-08-19
3,2025-08-20 00:00:00+07:00,2025-08-20T07:00:00+07:00,0.0,477,NMPT,2025-08-19
4,2025-08-20 00:00:00+07:00,2025-08-20T07:00:00+07:00,0.0,476,SRKT,2025-08-19

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-13.csv
🔹 Shape: (889, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-14 00:00:00+07:00,2025-08-14T07:00:00+07:00,0.4,1109578,ONE089,2025-08-13
1,2025-08-14 00:00:00+07:00,2025-08-14T07:00:00+07:00,0.0,1106453,TCP007,2025-08-13
2,2025-08-14 00:00:00+07:00,2025-08-14T07:00:00+07:00,0.0,80,CPY004,2025-08-13
3,2025-08-14 00:00:00+07:00,2025-08-14T07:00:00+07:00,0.0,492334,HDA002,2025-08-13
4,2025-08-14 00:00:00+07:00,2025-08-14T07:00:00+07:00,0.0,771,KKCN,2025-08-13

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-05.csv
🔹 Shape: (884, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,13885,SWR018,2025-08-05
1,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,253,THAT,2025-08-05
2,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,315,KON003,2025-08-05
3,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.4,283,VLGE02,2025-08-05
4,2025-08-06 00:00:00+07:00,2025-08-06T07:00:00+07:00,0.0,447,THCG,2025-08-05

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-30.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-31 00:00:00+07:00,2025-08-31T07:00:00+07:00,0.2,167,NYK014,2025-08-30
1,2025-08-31 00:00:00+07:00,2025-08-31T07:00:00+07:00,0.0,13877,SWR010,2025-08-30
2,2025-08-31 00:00:00+07:00,2025-08-31T07:00:00+07:00,0.2,533,YOM001,2025-08-30
3,2025-08-31 00:00:00+07:00,2025-08-31T07:00:00+07:00,0.0,489,YOM010,2025-08-30
4,2025-08-31 00:00:00+07:00,2025-08-31T07:00:00+07:00,0.0,130,MMNY,2025-08-30

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-11.csv
🔹 Shape: (891, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-12 00:00:00+07:00,2025-08-12T07:00:00+07:00,0.0,656,WCTK,2025-08-11
1,2025-08-12 00:00:00+07:00,2025-08-12T07:00:00+07:00,0.0,223,WEI022,2025-08-11
2,2025-08-12 00:00:00+07:00,2025-08-12T07:00:00+07:00,0.0,588,TKFA,2025-08-11
3,2025-08-12 00:00:00+07:00,2025-08-12T07:00:00+07:00,4.2,492350,ATG081,2025-08-11
4,2025-08-12 00:00:00+07:00,2025-08-12T07:00:00+07:00,10.4,307,WEI011,2025-08-11

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-31.csv
🔹 Shape: (1268, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id           float64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-01 00:00:00+07:00,2025-09-01T07:00:00+07:00,0.2,NaN,ACRU,2025-08-31
1,2025-09-01 00:00:00+07:00,2025-09-01T07:00:00+07:00,0.0,NaN,AIT001,2025-08-31
2,2025-09-01 00:00:00+07:00,2025-09-01T07:00:00+07:00,0.2,NaN,AIT002,2025-08-31
3,2025-09-01 00:00:00+07:00,2025-09-01T07:00:00+07:00,0.2,NaN,AIT005,2025-08-31
4,2025-09-01 00:00:00+07:00,2025-09-01T07:00:00+07:00,2.6,NaN,AIT008,2025-08-31

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-06.csv
🔹 Shape: (884, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-07 00:00:00+07:00,2025-08-07T07:00:00+07:00,0.0,1109493,ONE004,2025-08-06
1,2025-08-07 00:00:00+07:00,2025-08-07T07:00:00+07:00,2.0,510,NAN001,2025-08-06
2,2025-08-07 00:00:00+07:00,2025-08-07T07:00:00+07:00,0.0,740812,KWN003,2025-08-06
3,2025-08-07 00:00:00+07:00,2025-08-07T07:00:00+07:00,7.4,558,HSYO,2025-08-06
4,2025-08-07 00:00:00+07:00,2025-08-07T07:00:00+07:00,10.2,245,MUN009,2025-08-06

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-14.csv
🔹 Shape: (885, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,0.0,61,LBI002,2025-08-14
1,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,39.6,62,LNR1,2025-08-14
2,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,3.8,64,NMKH,2025-08-14
3,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,0.6,415,CGDO,2025-08-14
4,2025-08-15 00:00:00+07:00,2025-08-15T07:00:00+07:00,0.0,414,CHM004,2025-08-14

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-16.csv
🔹 Shape: (885, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-17 00:00:00+07:00,2025-08-17T07:00:00+07:00,0.2,1109568,ONE079,2025-08-16
1,2025-08-17 00:00:00+07:00,2025-08-17T07:00:00+07:00,1.0,1109567,ONE078,2025-08-16
2,2025-08-17 00:00:00+07:00,2025-08-17T07:00:00+07:00,0.0,849,JNA001,2025-08-16
3,2025-08-17 00:00:00+07:00,2025-08-17T07:00:00+07:00,0.2,237,VLGE21,2025-08-16
4,2025-08-17 00:00:00+07:00,2025-08-17T07:00:00+07:00,4.6,238,MUN014,2025-08-16

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-25.csv
🔹 Shape: (895, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-26 00:00:00+07:00,2025-08-26T07:00:00+07:00,0.0,492324,ATG101,2025-08-25
1,2025-08-26 00:00:00+07:00,2025-08-26T07:00:00+07:00,0.0,269,CHI011,2025-08-25
2,2025-08-26 00:00:00+07:00,2025-08-26T07:00:00+07:00,0.0,747,BKK019,2025-08-25
3,2025-08-26 00:00:00+07:00,2025-08-26T07:00:00+07:00,0.0,156,BPK004,2025-08-25
4,2025-08-26 00:00:00+07:00,2025-08-26T07:00:00+07:00,0.2,492355,ATG111,2025-08-25

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-24.csv
🔹 Shape: (878, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-25 00:00:00+07:00,2025-08-25T07:00:00+07:00,0.0,25,BKNH,2025-08-24
1,2025-08-25 00:00:00+07:00,2025-08-25T07:00:00+07:00,0.0,1093079,CHAU01,2025-08-24
2,2025-08-25 00:00:00+07:00,2025-08-25T07:00:00+07:00,5.2,492355,ATG111,2025-08-24
3,2025-08-25 00:00:00+07:00,2025-08-25T07:00:00+07:00,0.0,1082427,CHK001,2025-08-24
4,2025-08-25 00:00:00+07:00,2025-08-24T07:00:00+07:00,0.0,126,BTCH,2025-08-24

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-15.csv
🔹 Shape: (882, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-16 00:00:00+07:00,2025-08-16T07:00:00+07:00,7.0,13882,SWR015,2025-08-15
1,2025-08-16 00:00:00+07:00,2025-08-16T07:00:00+07:00,1.6,13883,SWR016,2025-08-15
2,2025-08-16 00:00:00+07:00,2025-08-16T07:00:00+07:00,64.2,13885,SWR018,2025-08-15
3,2025-08-16 00:00:00+07:00,2025-08-16T07:00:00+07:00,45.8,13886,SWR019,2025-08-15
4,2025-08-16 00:00:00+07:00,2025-08-16T07:00:00+07:00,42.2,13887,SWR020,2025-08-15

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-08.csv
🔹 Shape: (888, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-09 00:00:00+07:00,2025-08-09T07:00:00+07:00,9.2,117,RAY004,2025-08-08
1,2025-08-09 00:00:00+07:00,2025-08-09T07:00:00+07:00,48.8,1109568,ONE079,2025-08-08
2,2025-08-09 00:00:00+07:00,2025-08-09T07:00:00+07:00,0.0,1109586,ONE097,2025-08-08
3,2025-08-09 00:00:00+07:00,2025-08-09T07:00:00+07:00,0.0,1117430,PYO003,2025-08-08
4,2025-08-09 00:00:00+07:00,2025-08-09T07:00:00+07:00,0.0,1109593,ONE104,2025-08-08

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-21.csv
🔹 Shape: (884, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-22 00:00:00+07:00,2025-08-22T07:00:00+07:00,28.6,135,VLGE03,2025-08-21
1,2025-08-22 00:00:00+07:00,2025-08-22T07:00:00+07:00,0.0,385582,TBW017,2025-08-21
2,2025-08-22 00:00:00+07:00,2025-08-22T07:00:00+07:00,26.0,731,THA005,2025-08-21
3,2025-08-22 00:00:00+07:00,2025-08-22T07:00:00+07:00,0.2,385581,TBW014,2025-08-21
4,2025-08-22 00:00:00+07:00,2025-08-22T07:00:00+07:00,0.0,474,TRON,2025-08-21

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-18.csv
🔹 Shape: (887, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-19 00:00:00+07:00,2025-08-19T07:00:00+07:00,0.0,420,MNDM,2025-08-18
1,2025-08-19 00:00:00+07:00,2025-08-19T07:00:00+07:00,0.0,657,NAN012,2025-08-18
2,2025-08-19 00:00:00+07:00,2025-08-19T07:00:00+07:00,0.4,675,NAN013,2025-08-18
3,2025-08-19 00:00:00+07:00,2025-08-19T07:00:00+07:00,0.0,1108707,TCP013,2025-08-18
4,2025-08-19 00:00:00+07:00,2025-08-19T07:00:00+07:00,0.0,1107582,TCP012,2025-08-18

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-23.csv
🔹 Shape: (882, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-24 00:00:00+07:00,2025-08-24T07:00:00+07:00,10.6,1198628,TRD007,2025-08-23
1,2025-08-24 00:00:00+07:00,2025-08-24T07:00:00+07:00,0.0,479233,TBW025,2025-08-23
2,2025-08-24 00:00:00+07:00,2025-08-24T07:00:00+07:00,0.0,655,TSLM,2025-08-23
3,2025-08-24 00:00:00+07:00,2025-08-24T07:00:00+07:00,4.8,135,VLGE03,2025-08-23
4,2025-08-24 00:00:00+07:00,2025-08-24T07:00:00+07:00,0.6,746,THA011,2025-08-23

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-22.csv
🔹 Shape: (882, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-23 00:00:00+07:00,2025-08-23T07:00:00+07:00,35.2,135,VLGE03,2025-08-22
1,2025-08-23 00:00:00+07:00,2025-08-23T07:00:00+07:00,0.0,581,TTKO,2025-08-22
2,2025-08-23 00:00:00+07:00,2025-08-23T07:00:00+07:00,0.2,417,VLGE04,2025-08-22
3,2025-08-23 00:00:00+07:00,2025-08-23T07:00:00+07:00,2.2,166,TLAN,2025-08-22
4,2025-08-23 00:00:00+07:00,2025-08-23T07:00:00+07:00,14.6,821,TPI005,2025-08-22

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-12.csv
🔹 Shape: (890, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-13 00:00:00+07:00,2025-08-13T07:00:00+07:00,5.4,24,BKK018,2025-08-12
1,2025-08-13 00:00:00+07:00,2025-08-13T07:00:00+07:00,2.4,492324,ATG101,2025-08-12
2,2025-08-13 00:00:00+07:00,2025-08-13T07:00:00+07:00,0.0,1373273,NaN,2025-08-12
3,2025-08-13 00:00:00+07:00,2025-08-13T07:00:00+07:00,1.4,1116457,GOT001,2025-08-12
4,2025-08-13 00:00:00+07:00,2025-08-13T07:00:00+07:00,1.0,156,BPK004,2025-08-12

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-17.csv
🔹 Shape: (885, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-18 00:00:00+07:00,2025-08-18T07:00:00+07:00,0.8,602,NKYG,2025-08-17
1,2025-08-18 00:00:00+07:00,2025-08-18T07:00:00+07:00,0.2,87,WTSG,2025-08-17
2,2025-08-18 00:00:00+07:00,2025-08-18T07:00:00+07:00,0.4,88,HUKT,2025-08-17
3,2025-08-18 00:00:00+07:00,2025-08-18T07:00:00+07:00,0.8,89,CPY005,2025-08-17
4,2025-08-18 00:00:00+07:00,2025-08-18T07:00:00+07:00,0.2,93,HNKA,2025-08-17

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-28.csv
🔹 Shape: (891, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-29 00:00:00+07:00,2025-08-29T07:00:00+07:00,11.2,519,BOKA,2025-08-28
1,2025-08-29 00:00:00+07:00,2025-08-29T07:00:00+07:00,0.0,35,LK13,2025-08-28
2,2025-08-29 00:00:00+07:00,2025-08-29T07:00:00+07:00,0.6,189,NYK000,2025-08-28
3,2025-08-29 00:00:00+07:00,2025-08-29T07:00:00+07:00,1.2,1117430,PYO003,2025-08-28
4,2025-08-29 00:00:00+07:00,2025-08-29T07:00:00+07:00,0.0,1373689,NaN,2025-08-28

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-26.csv
🔹 Shape: (894, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-27 00:00:00+07:00,2025-08-27T07:00:00+07:00,0.0,103,TB0004,2025-08-26
1,2025-08-27 00:00:00+07:00,2025-08-27T07:00:00+07:00,66.4,501,TB0001,2025-08-26
2,2025-08-27 00:00:00+07:00,2025-08-27T07:00:00+07:00,4.4,1106457,TCP011,2025-08-26
3,2025-08-27 00:00:00+07:00,2025-08-27T07:00:00+07:00,0.0,1093079,CHAU01,2025-08-26
4,2025-08-27 00:00:00+07:00,2025-08-27T07:00:00+07:00,9.6,156,BPK004,2025-08-26

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-20.csv
🔹 Shape: (883, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-21 00:00:00+07:00,2025-08-21T07:00:00+07:00,0.0,80,CPY004,2025-08-20
1,2025-08-21 00:00:00+07:00,2025-08-21T07:00:00+07:00,0.0,81,MNRM,2025-08-20
2,2025-08-21 00:00:00+07:00,2025-08-21T07:00:00+07:00,0.2,83,CPY003,2025-08-20
3,2025-08-21 00:00:00+07:00,2025-08-21T07:00:00+07:00,0.0,87,WTSG,2025-08-20
4,2025-08-21 00:00:00+07:00,2025-08-21T07:00:00+07:00,1.4,88,HUKT,2025-08-20

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-10.csv
🔹 Shape: (893, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-11 00:00:00+07:00,2025-08-11T07:00:00+07:00,20.6,941,VLGE06,2025-08-10
1,2025-08-11 00:00:00+07:00,2025-08-11T07:00:00+07:00,0.0,492357,ATG121,2025-08-10
2,2025-08-11 00:00:00+07:00,2025-08-11T07:00:00+07:00,0.2,224,WEI021,2025-08-10
3,2025-08-11 00:00:00+07:00,2025-08-11T07:00:00+07:00,0.0,492362,ATG142,2025-08-10
4,2025-08-11 00:00:00+07:00,2025-08-11T07:00:00+07:00,0.0,492351,ATG082,2025-08-10

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-09.csv
🔹 Shape: (890, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-10 00:00:00+07:00,2025-08-10T07:00:00+07:00,0.0,1109565,ONE076,2025-08-09
1,2025-08-10 00:00:00+07:00,2025-08-10T07:00:00+07:00,0.0,1109511,ONE022,2025-08-09
2,2025-08-10 00:00:00+07:00,2025-08-10T07:00:00+07:00,0.0,1198299,PIN009,2025-08-09
3,2025-08-10 00:00:00+07:00,2025-08-10T07:00:00+07:00,3.0,1109510,ONE021,2025-08-09
4,2025-08-10 00:00:00+07:00,2025-08-10T07:00:00+07:00,0.0,709,RAJ002,2025-08-09

--------------------------------------------------------------------------------
📂 Folder: 2025-08
📄 File: HII_daily_rainfall_2025-08-29.csv
🔹 Shape: (897, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-30 00:00:00+07:00,2025-08-30T07:00:00+07:00,0.0,533,YOM001,2025-08-29
1,2025-08-30 00:00:00+07:00,2025-08-30T07:00:00+07:00,0.0,385579,TBW008,2025-08-29
2,2025-08-30 00:00:00+07:00,2025-08-30T07:00:00+07:00,2.8,189,NYK000,2025-08-29
3,2025-08-30 00:00:00+07:00,2025-08-30T07:00:00+07:00,0.0,443,LMPN,2025-08-29
4,2025-08-30 00:00:00+07:00,2025-08-30T07:00:00+07:00,0.0,720,BOP1,2025-08-29

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-07.csv
🔹 Shape: (923, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,417,VLGE04,2025-10-07
1,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,464,WAN002,2025-10-07
2,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,898,VLGE42,2025-10-07
3,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.2,1198626,TRD005,2025-10-07
4,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,698,WCBR,2025-10-07

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-14.csv
🔹 Shape: (936, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-15 00:00:00+07:00,2025-10-14T07:00:00+07:00,9.0,438,WGHG,2025-10-14
1,2025-10-15 00:00:00+07:00,2025-10-14T07:00:00+07:00,31.2,520,VLGE19,2025-10-14
2,2025-10-15 00:00:00+07:00,2025-10-14T07:00:00+07:00,0.0,60,WSPR,2025-10-14
3,2025-10-15 00:00:00+07:00,2025-10-14T07:00:00+07:00,5.2,883,VLGE29,2025-10-14
4,2025-10-15 00:00:00+07:00,2025-10-14T07:00:00+07:00,2.4,293,VLGE14,2025-10-14

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-22.csv
🔹 Shape: (972, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-23 00:00:00+07:00,2025-10-22T07:00:00+07:00,0.0,640,YOM012,2025-10-22
1,2025-10-23 00:00:00+07:00,2025-10-22T07:00:00+07:00,0.0,1106449,TCP003,2025-10-22
2,2025-10-23 00:00:00+07:00,2025-10-22T07:00:00+07:00,0.0,508,PUAA,2025-10-22
3,2025-10-23 00:00:00+07:00,2025-10-22T07:00:00+07:00,0.0,1109545,ONE056,2025-10-22
4,2025-10-23 00:00:00+07:00,2025-10-22T07:00:00+07:00,0.0,564,MSRM,2025-10-22

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-01.csv
🔹 Shape: (915, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-02 00:00:00+07:00,2025-10-01T07:00:00+07:00,0.2,812,TPI004,2025-10-01
1,2025-10-02 00:00:00+07:00,2025-10-01T07:00:00+07:00,10.8,688,TPKO,2025-10-01
2,2025-10-02 00:00:00+07:00,2025-10-01T07:00:00+07:00,0.0,746,THA011,2025-10-01
3,2025-10-02 00:00:00+07:00,2025-10-01T07:00:00+07:00,2.4,1198626,TRD005,2025-10-01
4,2025-10-02 00:00:00+07:00,2025-10-01T07:00:00+07:00,0.0,227,UDMS,2025-10-01

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-10.csv
🔹 Shape: (930, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-11 00:00:00+07:00,2025-10-10T07:00:00+07:00,0.0,894,STH024,2025-10-10
1,2025-10-11 00:00:00+07:00,2025-10-10T07:00:00+07:00,0.0,740539,AIT010,2025-10-10
2,2025-10-11 00:00:00+07:00,2025-10-10T07:00:00+07:00,4.4,628,PIN001,2025-10-10
3,2025-10-11 00:00:00+07:00,2025-10-10T07:00:00+07:00,0.0,740538,AIT009,2025-10-10
4,2025-10-11 00:00:00+07:00,2025-10-10T07:00:00+07:00,0.0,637,UPCT,2025-10-10

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-12.csv
🔹 Shape: (937, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-13 00:00:00+07:00,2025-10-12T07:00:00+07:00,0.0,608,VLGE15,2025-10-12
1,2025-10-13 00:00:00+07:00,2025-10-12T07:00:00+07:00,3.6,457841,VLGE49,2025-10-12
2,2025-10-13 00:00:00+07:00,2025-10-12T07:00:00+07:00,3.4,293,VLGE14,2025-10-12
3,2025-10-13 00:00:00+07:00,2025-10-12T07:00:00+07:00,0.0,438,WGHG,2025-10-12
4,2025-10-13 00:00:00+07:00,2025-10-12T07:00:00+07:00,0.0,540,VLGE31,2025-10-12

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-16.csv
🔹 Shape: (940, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-17 00:00:00+07:00,2025-10-16T07:00:00+07:00,0.4,415,CGDO,2025-10-16
1,2025-10-17 00:00:00+07:00,2025-10-16T07:00:00+07:00,0.0,771,KKCN,2025-10-16
2,2025-10-17 00:00:00+07:00,2025-10-16T07:00:00+07:00,0.0,1601344,NaN,2025-10-16
3,2025-10-17 00:00:00+07:00,2025-10-16T07:00:00+07:00,0.8,1601346,NaN,2025-10-16
4,2025-10-17 00:00:00+07:00,2025-10-16T07:00:00+07:00,20.8,129,KSNG,2025-10-16

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-13.csv
🔹 Shape: (933, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-14 00:00:00+07:00,2025-10-13T07:00:00+07:00,43.8,263,WEI112,2025-10-13
1,2025-10-14 00:00:00+07:00,2025-10-13T07:00:00+07:00,0.0,825,VLGE16,2025-10-13
2,2025-10-14 00:00:00+07:00,2025-10-13T07:00:00+07:00,2.2,668,VLGE12,2025-10-13
3,2025-10-14 00:00:00+07:00,2025-10-13T07:00:00+07:00,16.2,674,WGTG,2025-10-13
4,2025-10-14 00:00:00+07:00,2025-10-13T07:00:00+07:00,0.2,712,VLGE30,2025-10-13

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-04.csv
🔹 Shape: (920, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-05 00:00:00+07:00,2025-10-04T07:00:00+07:00,0.0,221,TLPC,2025-10-04
1,2025-10-05 00:00:00+07:00,2025-10-04T07:00:00+07:00,44.0,744,TANA,2025-10-04
2,2025-10-05 00:00:00+07:00,2025-10-04T07:00:00+07:00,0.0,441,TB0007,2025-10-04
3,2025-10-05 00:00:00+07:00,2025-10-04T07:00:00+07:00,0.0,13902,SWR035,2025-10-04
4,2025-10-05 00:00:00+07:00,2025-10-04T07:00:00+07:00,0.4,1094448,TADE01,2025-10-04

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-06.csv
🔹 Shape: (927, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-07 00:00:00+07:00,2025-10-06T07:00:00+07:00,0.0,780,BSVT,2025-10-06
1,2025-10-07 00:00:00+07:00,2025-10-06T07:00:00+07:00,0.8,404,BPUN,2025-10-06
2,2025-10-07 00:00:00+07:00,2025-10-06T07:00:00+07:00,0.2,205,BSDE,2025-10-06
3,2025-10-07 00:00:00+07:00,2025-10-06T07:00:00+07:00,0.0,173,BSCL,2025-10-06
4,2025-10-07 00:00:00+07:00,2025-10-06T07:00:00+07:00,0.0,151,BPK003,2025-10-06

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-20.csv
🔹 Shape: (961, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-21 00:00:00+07:00,2025-10-20T07:00:00+07:00,0.0,1107582,TCP012,2025-10-20
1,2025-10-21 00:00:00+07:00,2025-10-20T07:00:00+07:00,0.0,508,PUAA,2025-10-20
2,2025-10-21 00:00:00+07:00,2025-10-20T07:00:00+07:00,0.0,1601329,NaN,2025-10-20
3,2025-10-21 00:00:00+07:00,2025-10-20T07:00:00+07:00,0.0,1109586,ONE097,2025-10-20
4,2025-10-21 00:00:00+07:00,2025-10-20T07:00:00+07:00,0.0,1106449,TCP003,2025-10-20

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-23.csv
🔹 Shape: (975, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,385581,TBW014,2025-10-23
1,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,722,POCG,2025-10-23
2,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,839,VLGE17,2025-10-23
3,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,558,HSYO,2025-10-23
4,2025-10-24 00:00:00+07:00,2025-10-23T07:00:00+07:00,0.0,674,WGTG,2025-10-23

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-03.csv
🔹 Shape: (919, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-04 00:00:00+07:00,2025-10-03T07:00:00+07:00,31.0,104,TB0005,2025-10-03
1,2025-10-04 00:00:00+07:00,2025-10-03T07:00:00+07:00,7.2,518,STSK,2025-10-03
2,2025-10-04 00:00:00+07:00,2025-10-03T07:00:00+07:00,14.2,13902,SWR035,2025-10-03
3,2025-10-04 00:00:00+07:00,2025-10-03T07:00:00+07:00,0.2,836,TMLI,2025-10-03
4,2025-10-04 00:00:00+07:00,2025-10-03T07:00:00+07:00,0.6,13903,SWR036,2025-10-03

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-17.csv
🔹 Shape: (943, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-18 00:00:00+07:00,2025-10-17T07:00:00+07:00,0.6,723,DNCM,2025-10-17
1,2025-10-18 00:00:00+07:00,2025-10-17T07:00:00+07:00,19.0,1109551,ONE062,2025-10-17
2,2025-10-18 00:00:00+07:00,2025-10-17T07:00:00+07:00,0.0,748,THA008,2025-10-17
3,2025-10-18 00:00:00+07:00,2025-10-17T07:00:00+07:00,3.8,1109552,ONE063,2025-10-17
4,2025-10-18 00:00:00+07:00,2025-10-17T07:00:00+07:00,0.0,411,VLGE25,2025-10-17

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-02.csv
🔹 Shape: (914, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-03 00:00:00+07:00,2025-10-02T07:00:00+07:00,0.2,869,TNG001,2025-10-02
1,2025-10-03 00:00:00+07:00,2025-10-02T07:00:00+07:00,0.0,13901,SWR034,2025-10-02
2,2025-10-03 00:00:00+07:00,2025-10-02T07:00:00+07:00,0.0,746,THA011,2025-10-02
3,2025-10-03 00:00:00+07:00,2025-10-02T07:00:00+07:00,0.2,13903,SWR036,2025-10-02
4,2025-10-03 00:00:00+07:00,2025-10-02T07:00:00+07:00,0.0,192,TON001,2025-10-02

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-15.csv
🔹 Shape: (940, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-16 00:00:00+07:00,2025-10-15T07:00:00+07:00,12.6,540,VLGE31,2025-10-15
1,2025-10-16 00:00:00+07:00,2025-10-15T07:00:00+07:00,0.0,272,WEI092,2025-10-15
2,2025-10-16 00:00:00+07:00,2025-10-15T07:00:00+07:00,0.0,674,WGTG,2025-10-15
3,2025-10-16 00:00:00+07:00,2025-10-15T07:00:00+07:00,78.0,678,WTLG,2025-10-15
4,2025-10-16 00:00:00+07:00,2025-10-15T07:00:00+07:00,10.0,941,VLGE06,2025-10-15

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-09.csv
🔹 Shape: (926, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-10 00:00:00+07:00,2025-10-10T00:00:00+07:00,0.0,310,ACRU,2025-10-09
1,2025-10-10 00:00:00+07:00,2025-10-10T00:00:00+07:00,17.0,575565,BKC001,2025-10-09
2,2025-10-10 00:00:00+07:00,2025-10-10T00:00:00+07:00,0.2,243,KNDG,2025-10-09
3,2025-10-10 00:00:00+07:00,2025-10-10T00:00:00+07:00,0.0,740539,AIT010,2025-10-09
4,2025-10-10 00:00:00+07:00,2025-10-10T00:00:00+07:00,0.0,714,KRN001,2025-10-09

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-21.csv
🔹 Shape: (962, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-22 00:00:00+07:00,2025-10-21T07:00:00+07:00,20.2,1109524,ONE035,2025-10-21
1,2025-10-22 00:00:00+07:00,2025-10-21T07:00:00+07:00,0.0,1109586,ONE097,2025-10-21
2,2025-10-22 00:00:00+07:00,2025-10-21T07:00:00+07:00,0.6,881,STH015,2025-10-21
3,2025-10-22 00:00:00+07:00,2025-10-21T07:00:00+07:00,0.8,868,HYOD,2025-10-21
4,2025-10-22 00:00:00+07:00,2025-10-21T07:00:00+07:00,0.0,1107582,TCP012,2025-10-21

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-19.csv
🔹 Shape: (955, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-20 00:00:00+07:00,2025-10-19T07:00:00+07:00,0.0,1601356,NaN,2025-10-19
1,2025-10-20 00:00:00+07:00,2025-10-19T07:00:00+07:00,0.0,908,STH016,2025-10-19
2,2025-10-20 00:00:00+07:00,2025-10-19T07:00:00+07:00,2.4,614,KGLN,2025-10-19
3,2025-10-20 00:00:00+07:00,2025-10-19T07:00:00+07:00,10.4,783,WWST,2025-10-19
4,2025-10-20 00:00:00+07:00,2025-10-19T07:00:00+07:00,0.0,640,YOM012,2025-10-19

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-05.csv
🔹 Shape: (925, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-06 00:00:00+07:00,2025-10-05T07:00:00+07:00,0.0,840,BPLA,2025-10-05
1,2025-10-06 00:00:00+07:00,2025-10-05T07:00:00+07:00,0.8,205,BSDE,2025-10-05
2,2025-10-06 00:00:00+07:00,2025-10-05T07:00:00+07:00,19.4,173,BSCL,2025-10-05
3,2025-10-06 00:00:00+07:00,2025-10-05T07:00:00+07:00,12.8,151,BPK003,2025-10-05
4,2025-10-06 00:00:00+07:00,2025-10-05T07:00:00+07:00,0.0,13890,SWR023,2025-10-05

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-11.csv
🔹 Shape: (929, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-12 00:00:00+07:00,2025-10-11T07:00:00+07:00,0.0,384,WEI062,2025-10-11
1,2025-10-12 00:00:00+07:00,2025-10-11T07:00:00+07:00,3.0,1109589,ONE100,2025-10-11
2,2025-10-12 00:00:00+07:00,2025-10-11T07:00:00+07:00,0.4,326,PHON,2025-10-11
3,2025-10-12 00:00:00+07:00,2025-10-11T07:00:00+07:00,0.0,65,SBT1,2025-10-11
4,2025-10-12 00:00:00+07:00,2025-10-11T07:00:00+07:00,5.8,1132568,ONE109,2025-10-11

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-08.csv
🔹 Shape: (926, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-09 00:00:00+07:00,2025-10-08T07:00:00+07:00,0.0,379,VLGE43,2025-10-08
1,2025-10-09 00:00:00+07:00,2025-10-08T07:00:00+07:00,0.0,89,CPY005,2025-10-08
2,2025-10-09 00:00:00+07:00,2025-10-08T07:00:00+07:00,0.0,83,CPY003,2025-10-08
3,2025-10-09 00:00:00+07:00,2025-10-08T07:00:00+07:00,0.0,525,WBYN,2025-10-08
4,2025-10-09 00:00:00+07:00,2025-10-08T07:00:00+07:00,12.4,134,TRD004,2025-10-08

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-18.csv
🔹 Shape: (951, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-19 00:00:00+07:00,2025-10-18T07:00:00+07:00,0.4,832,BBHN,2025-10-18
1,2025-10-19 00:00:00+07:00,2025-10-18T07:00:00+07:00,0.0,1601346,NaN,2025-10-18
2,2025-10-19 00:00:00+07:00,2025-10-18T07:00:00+07:00,0.0,218,MUN003,2025-10-18
3,2025-10-19 00:00:00+07:00,2025-10-18T07:00:00+07:00,0.0,771,KKCN,2025-10-18
4,2025-10-19 00:00:00+07:00,2025-10-18T07:00:00+07:00,0.0,549,DIWO,2025-10-18

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-27.csv
🔹 Shape: (1001, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-28 00:00:00+07:00,2025-10-27T07:00:00+07:00,40.0,13883,SWR016,2025-10-27
1,2025-10-28 00:00:00+07:00,2025-10-27T07:00:00+07:00,0.0,169,PRC004,2025-10-27
2,2025-10-28 00:00:00+07:00,2025-10-27T07:00:00+07:00,0.0,783,WWST,2025-10-27
3,2025-10-28 00:00:00+07:00,2025-10-27T07:00:00+07:00,0.0,672,WTBT,2025-10-27
4,2025-10-28 00:00:00+07:00,2025-10-27T07:00:00+07:00,0.0,731,THA005,2025-10-27

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-31.csv
🔹 Shape: (1001, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-01 00:00:00+07:00,2025-10-31T07:00:00+07:00,8.4,492333,HDA001,2025-10-31
1,2025-11-01 00:00:00+07:00,2025-10-31T07:00:00+07:00,0.2,13899,SWR032,2025-10-31
2,2025-11-01 00:00:00+07:00,2025-10-31T07:00:00+07:00,0.0,886,STH002,2025-10-31
3,2025-11-01 00:00:00+07:00,2025-10-31T07:00:00+07:00,4.2,13896,SWR029,2025-10-31
4,2025-11-01 00:00:00+07:00,2025-10-31T07:00:00+07:00,0.2,896,STH004,2025-10-31

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-26.csv
🔹 Shape: (995, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-27 00:00:00+07:00,2025-10-26T07:00:00+07:00,0.0,1109578,ONE089,2025-10-26
1,2025-10-27 00:00:00+07:00,2025-10-26T07:00:00+07:00,0.4,1109572,ONE083,2025-10-26
2,2025-10-27 00:00:00+07:00,2025-10-26T07:00:00+07:00,0.0,662,CTKN,2025-10-26
3,2025-10-27 00:00:00+07:00,2025-10-26T07:00:00+07:00,0.0,164,WTCH,2025-10-26
4,2025-10-27 00:00:00+07:00,2025-10-26T07:00:00+07:00,0.0,645,YOM007,2025-10-26

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-25.csv
🔹 Shape: (989, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-26 00:00:00+07:00,2025-10-25T07:00:00+07:00,0.0,1198627,TRD006,2025-10-25
1,2025-10-26 00:00:00+07:00,2025-10-25T07:00:00+07:00,0.0,420,MNDM,2025-10-25
2,2025-10-26 00:00:00+07:00,2025-10-25T07:00:00+07:00,0.0,345,POCE,2025-10-25
3,2025-10-26 00:00:00+07:00,2025-10-25T07:00:00+07:00,0.0,1198626,TRD005,2025-10-25
4,2025-10-26 00:00:00+07:00,2025-10-25T07:00:00+07:00,4.8,811,KSOD,2025-10-25

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-30.csv
🔹 Shape: (994, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-31 00:00:00+07:00,2025-10-30T07:00:00+07:00,3.2,923,STH019,2025-10-30
1,2025-10-31 00:00:00+07:00,2025-10-30T07:00:00+07:00,0.0,414,CHM004,2025-10-30
2,2025-10-31 00:00:00+07:00,2025-10-30T07:00:00+07:00,3.8,202,BUGN,2025-10-30
3,2025-10-31 00:00:00+07:00,2025-10-30T07:00:00+07:00,0.6,464,WAN002,2025-10-30
4,2025-10-31 00:00:00+07:00,2025-10-30T07:00:00+07:00,0.0,897,STH017,2025-10-30

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-28.csv
🔹 Shape: (998, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-29 00:00:00+07:00,2025-10-28T07:00:00+07:00,0.0,164,WTCH,2025-10-28
1,2025-10-29 00:00:00+07:00,2025-10-28T07:00:00+07:00,0.0,1109573,ONE084,2025-10-28
2,2025-10-29 00:00:00+07:00,2025-10-28T07:00:00+07:00,0.0,731,THA005,2025-10-28
3,2025-10-29 00:00:00+07:00,2025-10-28T07:00:00+07:00,0.0,1109576,ONE087,2025-10-28
4,2025-10-29 00:00:00+07:00,2025-10-28T07:00:00+07:00,0.2,1373690,NaN,2025-10-28

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-29.csv
🔹 Shape: (996, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-30 00:00:00+07:00,2025-10-29T07:00:00+07:00,0.0,390,YBKM,2025-10-29
1,2025-10-30 00:00:00+07:00,2025-10-29T07:00:00+07:00,3.2,87,WTSG,2025-10-29
2,2025-10-30 00:00:00+07:00,2025-10-29T07:00:00+07:00,0.4,737,THA006,2025-10-29
3,2025-10-30 00:00:00+07:00,2025-10-29T07:00:00+07:00,0.0,645,YOM007,2025-10-29
4,2025-10-30 00:00:00+07:00,2025-10-29T07:00:00+07:00,1.6,1109576,ONE087,2025-10-29

--------------------------------------------------------------------------------
📂 Folder: 2025-10
📄 File: HII_daily_rainfall_2025-10-24.csv
🔹 Shape: (982, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-25 00:00:00+07:00,2025-10-24T07:00:00+07:00,0.0,432,KUAM,2025-10-24
1,2025-10-25 00:00:00+07:00,2025-10-24T07:00:00+07:00,0.0,237,VLGE21,2025-10-24
2,2025-10-25 00:00:00+07:00,2025-10-24T07:00:00+07:00,0.0,722,POCG,2025-10-24
3,2025-10-25 00:00:00+07:00,2025-10-24T07:00:00+07:00,9.0,140,HTTM,2025-10-24
4,2025-10-25 00:00:00+07:00,2025-10-24T07:00:00+07:00,0.0,111,NGSC,2025-10-24

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-09.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139,BLKO,2025-07-09
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277,BNAK,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156,BPK004,2025-07-09

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-10.csv
🔹 Shape: (900, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.2,447,THCG,2025-07-10
1,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.0,812,TPI004,2025-07-10
2,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,1.0,669,PPRM,2025-07-10
3,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.6,865,TNG002,2025-07-10
4,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.0,937,PNCR,2025-07-10

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-02.csv
🔹 Shape: (904, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-03 00:00:00+07:00,2025-07-03T07:00:00+07:00,2.2,928,SAY001,2025-07-02
1,2025-07-03 00:00:00+07:00,2025-07-03T07:00:00+07:00,18.2,921,STH022,2025-07-02
2,2025-07-03 00:00:00+07:00,2025-07-03T07:00:00+07:00,8.2,915,STH018,2025-07-02
3,2025-07-03 00:00:00+07:00,2025-07-03T07:00:00+07:00,49.8,888,STH001,2025-07-02
4,2025-07-03 00:00:00+07:00,2025-07-03T07:00:00+07:00,46.0,578,TAKI,2025-07-02

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-01.csv
🔹 Shape: (909, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-02 00:00:00+07:00,2025-07-02T07:00:00+07:00,0.0,589,MWOG,2025-07-01
1,2025-07-02 00:00:00+07:00,2025-07-02T07:00:00+07:00,0.0,564,MSRM,2025-07-01
2,2025-07-02 00:00:00+07:00,2025-07-02T07:00:00+07:00,34.0,4,CPY015,2025-07-01
3,2025-07-02 00:00:00+07:00,2025-07-02T07:00:00+07:00,0.2,867,KMSI,2025-07-01
4,2025-07-02 00:00:00+07:00,2025-07-02T07:00:00+07:00,38.2,54,CPY016,2025-07-01

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-06.csv
🔹 Shape: (905, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,256,MKTR,2025-07-06
1,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,492350,ATG081,2025-07-06
2,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,806,TTLG,2025-07-06
3,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.8,745748,AIT005,2025-07-06
4,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.4,1109493,ONE004,2025-07-06

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-11.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-12 00:00:00+07:00,2025-07-12T07:00:00+07:00,15.0,1109498,ONE009,2025-07-11
1,2025-07-12 00:00:00+07:00,2025-07-12T07:00:00+07:00,0.0,43,NOKK,2025-07-11
2,2025-07-12 00:00:00+07:00,2025-07-12T07:00:00+07:00,1.2,1109522,ONE033,2025-07-11
3,2025-07-12 00:00:00+07:00,2025-07-12T07:00:00+07:00,9.0,1109518,ONE029,2025-07-11
4,2025-07-12 00:00:00+07:00,2025-07-12T07:00:00+07:00,18.2,1109512,ONE023,2025-07-11

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-03.csv
🔹 Shape: (905, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-04 00:00:00+07:00,2025-07-04T07:00:00+07:00,0.2,49,CPY012,2025-07-03
1,2025-07-04 00:00:00+07:00,2025-07-04T07:00:00+07:00,0.0,841,CMP002,2025-07-03
2,2025-07-04 00:00:00+07:00,2025-07-04T07:00:00+07:00,0.0,819,BSBA,2025-07-03
3,2025-07-04 00:00:00+07:00,2025-07-04T07:00:00+07:00,0.8,205,BSDE,2025-07-03
4,2025-07-04 00:00:00+07:00,2025-07-04T07:00:00+07:00,1.2,215,BGRT,2025-07-03

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-08.csv
🔹 Shape: (905, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-09 00:00:00+07:00,2025-07-09T07:00:00+07:00,4.6,833,BGYN,2025-07-08
1,2025-07-09 00:00:00+07:00,2025-07-09T07:00:00+07:00,1.8,745748,AIT005,2025-07-08
2,2025-07-09 00:00:00+07:00,2025-07-09T07:00:00+07:00,4.8,151,BPK003,2025-07-08
3,2025-07-09 00:00:00+07:00,2025-07-09T07:00:00+07:00,0.0,575566,BKC002,2025-07-08
4,2025-07-09 00:00:00+07:00,2025-07-09T07:00:00+07:00,28.2,492345,ATG042,2025-07-08

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-07.csv
🔹 Shape: (901, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-08 00:00:00+07:00,2025-07-08T07:00:00+07:00,12.8,807,TLMU,2025-07-07
1,2025-07-08 00:00:00+07:00,2025-07-08T07:00:00+07:00,0.2,313,SOKL,2025-07-07
2,2025-07-08 00:00:00+07:00,2025-07-08T07:00:00+07:00,0.0,13869,SWR002,2025-07-07
3,2025-07-08 00:00:00+07:00,2025-07-08T07:00:00+07:00,1.6,385580,TBW009,2025-07-07
4,2025-07-08 00:00:00+07:00,2025-07-07T07:00:00+07:00,1.8,13871,SWR004,2025-07-07

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-04.csv
🔹 Shape: (904, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-05 00:00:00+07:00,2025-07-05T07:00:00+07:00,0.0,870,MDC005,2025-07-04
1,2025-07-05 00:00:00+07:00,2025-07-05T07:00:00+07:00,0.8,354,NEAK,2025-07-04
2,2025-07-05 00:00:00+07:00,2025-07-05T07:00:00+07:00,0.0,620,KGKG,2025-07-04
3,2025-07-05 00:00:00+07:00,2025-07-05T07:00:00+07:00,1.6,838,HJRN1,2025-07-04
4,2025-07-05 00:00:00+07:00,2025-07-05T07:00:00+07:00,5.4,275,KANG,2025-07-04

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-05.csv
🔹 Shape: (906, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-06 00:00:00+07:00,2025-07-06T07:00:00+07:00,0.0,492347,ATG052,2025-07-05
1,2025-07-06 00:00:00+07:00,2025-07-06T07:00:00+07:00,0.0,493,YOM004,2025-07-05
2,2025-07-06 00:00:00+07:00,2025-07-05T07:00:00+07:00,0.8,740540,AIT011,2025-07-05
3,2025-07-06 00:00:00+07:00,2025-07-06T07:00:00+07:00,13.0,1094448,TADE01,2025-07-05
4,2025-07-06 00:00:00+07:00,2025-07-06T07:00:00+07:00,0.0,517,NAMN,2025-07-05

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-14.csv
🔹 Shape: (895, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-15 00:00:00+07:00,2025-07-15T07:00:00+07:00,0.0,13883,SWR016,2025-07-14
1,2025-07-15 00:00:00+07:00,2025-07-15T07:00:00+07:00,0.2,396,SKM005,2025-07-14
2,2025-07-15 00:00:00+07:00,2025-07-15T07:00:00+07:00,0.0,718,NTST,2025-07-14
3,2025-07-15 00:00:00+07:00,2025-07-15T07:00:00+07:00,0.0,1373689,NaN,2025-07-14
4,2025-07-15 00:00:00+07:00,2025-07-15T07:00:00+07:00,0.0,328,PTYS,2025-07-14

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-25.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,2.6,372,NTTI,2025-07-25
1,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,2.8,572,CMSG,2025-07-25
2,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,28.8,1198298,PIN008,2025-07-25
3,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,0.0,667,NAN006,2025-07-25
4,2025-07-26 00:00:00+07:00,2025-07-26T07:00:00+07:00,0.0,117,RAY004,2025-07-25

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-24.csv
🔹 Shape: (898, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-25 00:00:00+07:00,2025-07-25T07:00:00+07:00,3.8,485,LPLE,2025-07-24
1,2025-07-25 00:00:00+07:00,2025-07-25T07:00:00+07:00,0.0,923,STH019,2025-07-24
2,2025-07-25 00:00:00+07:00,2025-07-25T07:00:00+07:00,2.2,13878,SWR011,2025-07-24
3,2025-07-25 00:00:00+07:00,2025-07-25T07:00:00+07:00,1.0,481,PICI,2025-07-24
4,2025-07-25 00:00:00+07:00,2025-07-25T07:00:00+07:00,0.0,353,PHPS,2025-07-24

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-13.csv
🔹 Shape: (896, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-14 00:00:00+07:00,2025-07-14T07:00:00+07:00,0.0,886,STH002,2025-07-13
1,2025-07-14 00:00:00+07:00,2025-07-14T07:00:00+07:00,0.0,896,STH004,2025-07-13
2,2025-07-14 00:00:00+07:00,2025-07-14T07:00:00+07:00,0.0,432,KUAM,2025-07-13
3,2025-07-14 00:00:00+07:00,2025-07-14T07:00:00+07:00,0.0,13888,SWR021,2025-07-13
4,2025-07-14 00:00:00+07:00,2025-07-14T07:00:00+07:00,0.2,304,SMSU,2025-07-13

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-20.csv
🔹 Shape: (901, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,435493,VLGE46,2025-07-20
1,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,265,BNLG,2025-07-20
2,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,4.4,549,DIWO,2025-07-20
3,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,539,CGKG,2025-07-20
4,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,901,PAT002,2025-07-20

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-27.csv
🔹 Shape: (893, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-28 00:00:00+07:00,2025-07-28T07:00:00+07:00,5.0,122,PNRN,2025-07-27
1,2025-07-28 00:00:00+07:00,2025-07-28T07:00:00+07:00,17.6,1109578,ONE089,2025-07-27
2,2025-07-28 00:00:00+07:00,2025-07-28T07:00:00+07:00,20.0,1512927,NaN,2025-07-27
3,2025-07-28 00:00:00+07:00,2025-07-28T07:00:00+07:00,0.0,722,POCG,2025-07-27
4,2025-07-28 00:00:00+07:00,2025-07-28T07:00:00+07:00,10.2,1109502,ONE013,2025-07-27

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-18.csv
🔹 Shape: (898, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-19 00:00:00+07:00,2025-07-19T07:00:00+07:00,2.4,750,THA009,2025-07-18
1,2025-07-19 00:00:00+07:00,2025-07-19T07:00:00+07:00,2.2,13879,SWR012,2025-07-18
2,2025-07-19 00:00:00+07:00,2025-07-19T07:00:00+07:00,0.0,1094448,TADE01,2025-07-18
3,2025-07-19 00:00:00+07:00,2025-07-19T07:00:00+07:00,0.0,12481,STU002,2025-07-18
4,2025-07-19 00:00:00+07:00,2025-07-19T07:00:00+07:00,0.0,650,SWKL,2025-07-18

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-26.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-27 00:00:00+07:00,2025-07-27T07:00:00+07:00,8.2,703,NMNO,2025-07-26
1,2025-07-27 00:00:00+07:00,2025-07-27T07:00:00+07:00,0.6,242,VLGE08,2025-07-26
2,2025-07-27 00:00:00+07:00,2025-07-27T07:00:00+07:00,7.8,547,CHR005,2025-07-26
3,2025-07-27 00:00:00+07:00,2025-07-27T07:00:00+07:00,1.2,1198297,PIN007,2025-07-26
4,2025-07-27 00:00:00+07:00,2025-07-27T07:00:00+07:00,0.0,13880,SWR013,2025-07-26

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-17.csv
🔹 Shape: (896, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-18 00:00:00+07:00,2025-07-18T07:00:00+07:00,0.0,13889,SWR022,2025-07-17
1,2025-07-18 00:00:00+07:00,2025-07-18T07:00:00+07:00,1.8,109,SWNG,2025-07-17
2,2025-07-18 00:00:00+07:00,2025-07-18T07:00:00+07:00,0.2,104,TB0005,2025-07-17
3,2025-07-18 00:00:00+07:00,2025-07-18T07:00:00+07:00,0.0,750,THA009,2025-07-17
4,2025-07-18 00:00:00+07:00,2025-07-18T07:00:00+07:00,0.0,12350,TNG006,2025-07-17

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-30.csv
🔹 Shape: (888, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-31 00:00:00+07:00,2025-07-31T07:00:00+07:00,0.0,1109564,ONE075,2025-07-30
1,2025-07-31 00:00:00+07:00,2025-07-31T07:00:00+07:00,0.0,1109526,ONE037,2025-07-30
2,2025-07-31 00:00:00+07:00,2025-07-31T07:00:00+07:00,0.0,1109562,ONE073,2025-07-30
3,2025-07-31 00:00:00+07:00,2025-07-31T07:00:00+07:00,5.6,532,PONG,2025-07-30
4,2025-07-31 00:00:00+07:00,2025-07-31T07:00:00+07:00,0.0,1109568,ONE079,2025-07-30

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-29.csv
🔹 Shape: (894, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-30 00:00:00+07:00,2025-07-30T07:00:00+07:00,0.0,1109586,ONE097,2025-07-29
1,2025-07-30 00:00:00+07:00,2025-07-30T07:00:00+07:00,0.2,1109501,ONE012,2025-07-29
2,2025-07-30 00:00:00+07:00,2025-07-30T07:00:00+07:00,15.2,1109583,ONE094,2025-07-29
3,2025-07-30 00:00:00+07:00,2025-07-30T07:00:00+07:00,0.0,616,PIN004,2025-07-29
4,2025-07-30 00:00:00+07:00,2025-07-30T07:00:00+07:00,1.0,1109585,ONE096,2025-07-29

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-31.csv
🔹 Shape: (893, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-01 00:00:00+07:00,2025-08-01T07:00:00+07:00,0.0,103,TB0004,2025-07-31
1,2025-08-01 00:00:00+07:00,2025-08-01T07:00:00+07:00,2.2,97,CMKK,2025-07-31
2,2025-08-01 00:00:00+07:00,2025-08-01T07:00:00+07:00,0.0,93,HNKA,2025-07-31
3,2025-08-01 00:00:00+07:00,2025-08-01T07:00:00+07:00,0.0,89,CPY005,2025-07-31
4,2025-08-01 00:00:00+07:00,2025-08-01T07:00:00+07:00,0.0,88,HUKT,2025-07-31

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-15.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-16 00:00:00+07:00,2025-07-16T07:00:00+07:00,10.4,1373689,NaN,2025-07-15
1,2025-07-16 00:00:00+07:00,2025-07-16T07:00:00+07:00,4.4,13873,SWR006,2025-07-15
2,2025-07-16 00:00:00+07:00,2025-07-16T07:00:00+07:00,0.0,162,PRC001,2025-07-15
3,2025-07-16 00:00:00+07:00,2025-07-15T07:00:00+07:00,44.4,13886,SWR019,2025-07-15
4,2025-07-16 00:00:00+07:00,2025-07-16T07:00:00+07:00,0.0,681,PPTC,2025-07-15

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-12.csv
🔹 Shape: (895, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-13 00:00:00+07:00,2025-07-13T07:00:00+07:00,0.0,564,MSRM,2025-07-12
1,2025-07-13 00:00:00+07:00,2025-07-13T07:00:00+07:00,0.0,489,YOM010,2025-07-12
2,2025-07-13 00:00:00+07:00,2025-07-13T07:00:00+07:00,0.0,680,YOM009,2025-07-12
3,2025-07-13 00:00:00+07:00,2025-07-13T07:00:00+07:00,0.0,253,THAT,2025-07-12
4,2025-07-13 00:00:00+07:00,2025-07-13T07:00:00+07:00,2.0,1198762,YOM016,2025-07-12

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-22.csv
🔹 Shape: (901, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-23 00:00:00+07:00,2025-07-23T07:00:00+07:00,18.8,660,NKTI,2025-07-22
1,2025-07-23 00:00:00+07:00,2025-07-23T07:00:00+07:00,0.0,539,CGKG,2025-07-22
2,2025-07-23 00:00:00+07:00,2025-07-23T07:00:00+07:00,1.0,57,CPY017,2025-07-22
3,2025-07-23 00:00:00+07:00,2025-07-23T07:00:00+07:00,0.2,326,PHON,2025-07-22
4,2025-07-23 00:00:00+07:00,2025-07-23T07:00:00+07:00,0.0,298,CHI001,2025-07-22

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-19.csv
🔹 Shape: (902, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-20 00:00:00+07:00,2025-07-20T07:00:00+07:00,13.2,714,KRN001,2025-07-19
1,2025-07-20 00:00:00+07:00,2025-07-20T07:00:00+07:00,9.8,750,THA009,2025-07-19
2,2025-07-20 00:00:00+07:00,2025-07-20T07:00:00+07:00,0.6,1106451,TCP005,2025-07-19
3,2025-07-20 00:00:00+07:00,2025-07-20T07:00:00+07:00,0.0,104,TB0005,2025-07-19
4,2025-07-20 00:00:00+07:00,2025-07-20T07:00:00+07:00,6.4,1107582,TCP012,2025-07-19

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-16.csv
🔹 Shape: (897, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-17 00:00:00+07:00,2025-07-17T07:00:00+07:00,0.0,681,PPTC,2025-07-16
1,2025-07-17 00:00:00+07:00,2025-07-17T07:00:00+07:00,0.2,1373689,NaN,2025-07-16
2,2025-07-17 00:00:00+07:00,2025-07-17T07:00:00+07:00,6.0,13874,SWR007,2025-07-16
3,2025-07-17 00:00:00+07:00,2025-07-17T07:00:00+07:00,50.4,650,SWKL,2025-07-16
4,2025-07-17 00:00:00+07:00,2025-07-17T07:00:00+07:00,28.4,649,SSRG,2025-07-16

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-21.csv
🔹 Shape: (901, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-22 00:00:00+07:00,2025-07-22T07:00:00+07:00,0.0,14,BKK004,2025-07-21
1,2025-07-22 00:00:00+07:00,2025-07-22T07:00:00+07:00,0.0,308,WEI012,2025-07-21
2,2025-07-22 00:00:00+07:00,2025-07-22T07:00:00+07:00,0.0,448,PASG,2025-07-21
3,2025-07-22 00:00:00+07:00,2025-07-22T07:00:00+07:00,0.0,1109529,ONE040,2025-07-21
4,2025-07-22 00:00:00+07:00,2025-07-22T07:00:00+07:00,1.6,12478,PCH003,2025-07-21

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-23.csv
🔹 Shape: (897, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-24 00:00:00+07:00,2025-07-24T07:00:00+07:00,17.0,57,CPY017,2025-07-23
1,2025-07-24 00:00:00+07:00,2025-07-24T07:00:00+07:00,1.0,305,CSMO,2025-07-23
2,2025-07-24 00:00:00+07:00,2025-07-24T07:00:00+07:00,49.4,519,BOKA,2025-07-23
3,2025-07-24 00:00:00+07:00,2025-07-24T07:00:00+07:00,0.0,273,NGPH,2025-07-23
4,2025-07-24 00:00:00+07:00,2025-07-24T07:00:00+07:00,0.0,400,PPAN,2025-07-23

--------------------------------------------------------------------------------
📂 Folder: 2025-07
📄 File: HII_daily_rainfall_2025-07-28.csv
🔹 Shape: (896, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-29 00:00:00+07:00,2025-07-29T07:00:00+07:00,0.0,1109580,ONE091,2025-07-28
1,2025-07-29 00:00:00+07:00,2025-07-29T07:00:00+07:00,0.4,536,RIKK,2025-07-28
2,2025-07-29 00:00:00+07:00,2025-07-29T07:00:00+07:00,19.2,1109519,ONE030,2025-07-28
3,2025-07-29 00:00:00+07:00,2025-07-29T07:00:00+07:00,0.0,669,PPRM,2025-07-28
4,2025-07-29 00:00:00+07:00,2025-07-29T07:00:00+07:00,31.4,1109506,ONE017,2025-07-28

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-23.csv
🔹 Shape: (907, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,2.4,1109572,ONE083,2025-09-23
1,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,0.8,672,WTBT,2025-09-23
2,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,23.4,671,DIV002,2025-09-23
3,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,0.2,854,TSDO,2025-09-23
4,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,0.2,611,DIV005,2025-09-23

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-28.csv
🔹 Shape: (906, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-29 00:00:00+07:00,2025-09-29T07:00:00+07:00,0.4,330,CHI005,2025-09-28
1,2025-09-29 00:00:00+07:00,2025-09-29T07:00:00+07:00,0.0,442,BMKN,2025-09-28
2,2025-09-29 00:00:00+07:00,2025-09-29T07:00:00+07:00,0.0,506,BLUG,2025-09-28
3,2025-09-29 00:00:00+07:00,2025-09-29T07:00:00+07:00,0.0,492347,ATG052,2025-09-28
4,2025-09-29 00:00:00+07:00,2025-09-29T07:00:00+07:00,8.6,1082427,CHK001,2025-09-28

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-12.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-13 00:00:00+07:00,2025-09-13T07:00:00+07:00,3.8,115,RAY001,2025-09-12
1,2025-09-13 00:00:00+07:00,2025-09-13T07:00:00+07:00,3.4,1601329,NaN,2025-09-12
2,2025-09-13 00:00:00+07:00,2025-09-13T07:00:00+07:00,19.0,1548591,NaN,2025-09-12
3,2025-09-13 00:00:00+07:00,2025-09-13T07:00:00+07:00,0.0,544,PADT,2025-09-12
4,2025-09-13 00:00:00+07:00,2025-09-13T07:00:00+07:00,0.0,554,PYMR,2025-09-12

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-26.csv
🔹 Shape: (901, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-27 00:00:00+07:00,2025-09-27T07:00:00+07:00,0.4,252,VLGE27,2025-09-26
1,2025-09-27 00:00:00+07:00,2025-09-27T07:00:00+07:00,0.8,11,BKK001,2025-09-26
2,2025-09-27 00:00:00+07:00,2025-09-27T07:00:00+07:00,0.0,269,CHI011,2025-09-26
3,2025-09-27 00:00:00+07:00,2025-09-27T07:00:00+07:00,2.8,720,BOP1,2025-09-26
4,2025-09-27 00:00:00+07:00,2025-09-27T07:00:00+07:00,0.0,662,CTKN,2025-09-26

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-02.csv
🔹 Shape: (1270, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id           float64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-03 00:00:00+07:00,2025-09-03T07:00:00+07:00,0.2,NaN,ACRU,2025-09-02
1,2025-09-03 00:00:00+07:00,2025-09-03T07:00:00+07:00,0.0,NaN,AIT001,2025-09-02
2,2025-09-03 00:00:00+07:00,2025-09-03T07:00:00+07:00,1.8,NaN,AIT002,2025-09-02
3,2025-09-03 00:00:00+07:00,2025-09-03T07:00:00+07:00,2.2,NaN,AIT005,2025-09-02
4,2025-09-03 00:00:00+07:00,2025-09-03T07:00:00+07:00,5.2,NaN,AIT008,2025-09-02

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-24.csv
🔹 Shape: (906, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-25 00:00:00+07:00,2025-09-25T07:00:00+07:00,0.0,1124861,NWSO,2025-09-24
1,2025-09-25 00:00:00+07:00,2025-09-25T07:00:00+07:00,0.2,1109530,ONE041,2025-09-24
2,2025-09-25 00:00:00+07:00,2025-09-25T07:00:00+07:00,0.0,741,NPNK,2025-09-24
3,2025-09-25 00:00:00+07:00,2025-09-25T07:00:00+07:00,0.0,1109568,ONE079,2025-09-24
4,2025-09-25 00:00:00+07:00,2025-09-25T07:00:00+07:00,0.2,587,SKG007,2025-09-24

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-15.csv
🔹 Shape: (902, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-16 00:00:00+07:00,2025-09-16T07:00:00+07:00,10.4,13886,SWR019,2025-09-15
1,2025-09-16 00:00:00+07:00,2025-09-16T07:00:00+07:00,1.0,880,STH012,2025-09-15
2,2025-09-16 00:00:00+07:00,2025-09-16T07:00:00+07:00,10.2,924,STH021,2025-09-15
3,2025-09-16 00:00:00+07:00,2025-09-16T07:00:00+07:00,15.8,13869,SWR002,2025-09-15
4,2025-09-16 00:00:00+07:00,2025-09-16T07:00:00+07:00,0.0,13889,SWR022,2025-09-15

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-03.csv
🔹 Shape: (899, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-04 00:00:00+07:00,2025-09-04T07:00:00+07:00,0.0,724,TPAE,2025-09-03
1,2025-09-04 00:00:00+07:00,2025-09-04T07:00:00+07:00,60.6,807,TLMU,2025-09-03
2,2025-09-04 00:00:00+07:00,2025-09-04T07:00:00+07:00,0.6,479241,TBW033,2025-09-03
3,2025-09-04 00:00:00+07:00,2025-09-04T07:00:00+07:00,8.4,871,TKRA,2025-09-03
4,2025-09-04 00:00:00+07:00,2025-09-04T07:00:00+07:00,0.0,1106454,TCP008,2025-09-03

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-20.csv
🔹 Shape: (904, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-21 00:00:00+07:00,2025-09-21T07:00:00+07:00,0.0,68,CPY007,2025-09-20
1,2025-09-21 00:00:00+07:00,2025-09-21T07:00:00+07:00,0.0,497,WCHN,2025-09-20
2,2025-09-21 00:00:00+07:00,2025-09-21T07:00:00+07:00,0.0,58,CPY008,2025-09-20
3,2025-09-21 00:00:00+07:00,2025-09-21T07:00:00+07:00,0.4,775,YKPC,2025-09-20
4,2025-09-21 00:00:00+07:00,2025-09-21T07:00:00+07:00,7.6,463,WAN003,2025-09-20

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-07.csv
🔹 Shape: (898, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-08 00:00:00+07:00,2025-09-08T07:00:00+07:00,0.0,783,WWST,2025-09-07
1,2025-09-08 00:00:00+07:00,2025-09-08T07:00:00+07:00,9.4,775,YKPC,2025-09-07
2,2025-09-08 00:00:00+07:00,2025-09-08T07:00:00+07:00,0.8,837,CCSS,2025-09-07
3,2025-09-08 00:00:00+07:00,2025-09-08T07:00:00+07:00,1.6,358,CHI012,2025-09-07
4,2025-09-08 00:00:00+07:00,2025-09-08T07:00:00+07:00,2.0,380,CHI013,2025-09-07

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-13.csv
🔹 Shape: (901, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-14 00:00:00+07:00,2025-09-14T07:00:00+07:00,1.2,1373692,NaN,2025-09-13
1,2025-09-14 00:00:00+07:00,2025-09-14T07:00:00+07:00,13.4,1601329,NaN,2025-09-13
2,2025-09-14 00:00:00+07:00,2025-09-14T07:00:00+07:00,24.0,1601342,NaN,2025-09-13
3,2025-09-14 00:00:00+07:00,2025-09-14T07:00:00+07:00,0.0,1109589,ONE100,2025-09-13
4,2025-09-14 00:00:00+07:00,2025-09-14T07:00:00+07:00,0.0,860,SLA002,2025-09-13

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-17.csv
🔹 Shape: (902, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-18 00:00:00+07:00,2025-09-18T07:00:00+07:00,0.0,923,STH019,2025-09-17
1,2025-09-18 00:00:00+07:00,2025-09-18T07:00:00+07:00,0.0,922,SAY002,2025-09-17
2,2025-09-18 00:00:00+07:00,2025-09-18T07:00:00+07:00,7.2,1106454,TCP008,2025-09-17
3,2025-09-18 00:00:00+07:00,2025-09-18T07:00:00+07:00,0.2,479233,TBW025,2025-09-17
4,2025-09-18 00:00:00+07:00,2025-09-18T07:00:00+07:00,0.0,536,RIKK,2025-09-17

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-04.csv
🔹 Shape: (894, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-05 00:00:00+07:00,2025-09-05T07:00:00+07:00,0.0,791,BTWN,2025-09-04
1,2025-09-05 00:00:00+07:00,2025-09-05T07:00:00+07:00,0.0,792,NKO002,2025-09-04
2,2025-09-05 00:00:00+07:00,2025-09-05T07:00:00+07:00,3.6,794,NPI001,2025-09-04
3,2025-09-05 00:00:00+07:00,2025-09-05T07:00:00+07:00,1.8,795,NKO001,2025-09-04
4,2025-09-05 00:00:00+07:00,2025-09-05T07:00:00+07:00,4.2,797,KKHA,2025-09-04

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-29.csv
🔹 Shape: (910, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-30 00:00:00+07:00,2025-09-29T07:00:00+07:00,0.4,433,SBRS,2025-09-29
1,2025-09-30 00:00:00+07:00,2025-09-29T07:00:00+07:00,2.6,283,VLGE02,2025-09-29
2,2025-09-30 00:00:00+07:00,2025-09-29T07:00:00+07:00,2.0,13883,SWR016,2025-09-29
3,2025-09-30 00:00:00+07:00,2025-09-29T07:00:00+07:00,2.6,192,TON001,2025-09-29
4,2025-09-30 00:00:00+07:00,2025-09-29T07:00:00+07:00,0.0,221,TLPC,2025-09-29

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-14.csv
🔹 Shape: (904, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-15 00:00:00+07:00,2025-09-15T07:00:00+07:00,23.8,479241,TBW033,2025-09-14
1,2025-09-15 00:00:00+07:00,2025-09-15T07:00:00+07:00,0.6,13888,SWR021,2025-09-14
2,2025-09-15 00:00:00+07:00,2025-09-15T07:00:00+07:00,0.0,251,PRST,2025-09-14
3,2025-09-15 00:00:00+07:00,2025-09-15T07:00:00+07:00,0.0,1106453,TCP007,2025-09-14
4,2025-09-15 00:00:00+07:00,2025-09-15T07:00:00+07:00,4.2,190,SKE001,2025-09-14

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-27.csv
🔹 Shape: (907, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-28 00:00:00+07:00,2025-09-28T07:00:00+07:00,10.0,1601361,NaN,2025-09-27
1,2025-09-28 00:00:00+07:00,2025-09-28T07:00:00+07:00,0.0,778,MDTG,2025-09-27
2,2025-09-28 00:00:00+07:00,2025-09-28T07:00:00+07:00,0.0,1601363,NaN,2025-09-27
3,2025-09-28 00:00:00+07:00,2025-09-28T07:00:00+07:00,0.0,897,STH017,2025-09-27
4,2025-09-28 00:00:00+07:00,2025-09-28T07:00:00+07:00,9.2,241,LNRG,2025-09-27

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: rain_hii_20250901.csv
🔹 Shape: (1276, 3)
🔹 Columns: ['station_code', 'measure_datetime', 'value']
🔹 Data types:
station_code         object
measure_datetime     object
value               float64
dtype: object
🔹 Head:

  station_code measure_datetime  value
0         ACRU       2025-09-01   15.6
1       AIT001       2025-09-01    0.4
2       AIT002       2025-09-01    0.2
3       AIT005       2025-09-01    0.6
4       AIT008       2025-09-01    2.6

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-06.csv
🔹 Shape: (897, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-07 00:00:00+07:00,2025-09-07T07:00:00+07:00,52.6,492370,ATG182,2025-09-06
1,2025-09-07 00:00:00+07:00,2025-09-07T07:00:00+07:00,0.2,1109584,ONE095,2025-09-06
2,2025-09-07 00:00:00+07:00,2025-09-07T07:00:00+07:00,8.8,1109583,ONE094,2025-09-06
3,2025-09-07 00:00:00+07:00,2025-09-07T07:00:00+07:00,0.2,1109581,ONE092,2025-09-06
4,2025-09-07 00:00:00+07:00,2025-09-07T07:00:00+07:00,1.2,1109580,ONE091,2025-09-06

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-21.csv
🔹 Shape: (908, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-22 00:00:00+07:00,2025-09-22T07:00:00+07:00,0.0,783,WWST,2025-09-21
1,2025-09-22 00:00:00+07:00,2025-09-22T07:00:00+07:00,0.0,740812,KWN003,2025-09-21
2,2025-09-22 00:00:00+07:00,2025-09-22T07:00:00+07:00,1.4,1140845,YOM013,2025-09-21
3,2025-09-22 00:00:00+07:00,2025-09-22T07:00:00+07:00,12.6,474,TRON,2025-09-21
4,2025-09-22 00:00:00+07:00,2025-09-22T07:00:00+07:00,29.6,678,WTLG,2025-09-21

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-01.csv
🔹 Shape: (1276, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id           float64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-02 00:00:00+07:00,2025-09-02T07:00:00+07:00,15.6,NaN,ACRU,2025-09-01
1,2025-09-02 00:00:00+07:00,2025-09-02T07:00:00+07:00,0.4,NaN,AIT001,2025-09-01
2,2025-09-02 00:00:00+07:00,2025-09-02T07:00:00+07:00,0.2,NaN,AIT002,2025-09-01
3,2025-09-02 00:00:00+07:00,2025-09-02T07:00:00+07:00,0.6,NaN,AIT005,2025-09-01
4,2025-09-02 00:00:00+07:00,2025-09-02T07:00:00+07:00,2.6,NaN,AIT008,2025-09-01

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-05.csv
🔹 Shape: (898, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-06 00:00:00+07:00,2025-09-06T07:00:00+07:00,6.2,340,BNPU,2025-09-05
1,2025-09-06 00:00:00+07:00,2025-09-06T07:00:00+07:00,11.8,50,LBI001,2025-09-05
2,2025-09-06 00:00:00+07:00,2025-09-06T07:00:00+07:00,0.0,51,PKH1,2025-09-05
3,2025-09-06 00:00:00+07:00,2025-09-06T07:00:00+07:00,5.4,54,CPY016,2025-09-05
4,2025-09-06 00:00:00+07:00,2025-09-06T07:00:00+07:00,0.0,57,CPY017,2025-09-05

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-18.csv
🔹 Shape: (900, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,0.0,335,KON004,2025-09-18
1,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,15.6,693,PAS001,2025-09-18
2,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,5.0,636,PPCT,2025-09-18
3,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,3.8,307,WEI011,2025-09-18
4,2025-09-19 00:00:00+07:00,2025-09-19T07:00:00+07:00,0.0,58,CPY008,2025-09-18

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-09.csv
🔹 Shape: (902, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-10 00:00:00+07:00,2025-09-10T07:00:00+07:00,6.8,499,YOM003,2025-09-09
1,2025-09-10 00:00:00+07:00,2025-09-10T07:00:00+07:00,0.4,664,YOM008,2025-09-09
2,2025-09-10 00:00:00+07:00,2025-09-10T07:00:00+07:00,0.0,647,YOM005,2025-09-09
3,2025-09-10 00:00:00+07:00,2025-09-10T07:00:00+07:00,15.4,653,YOM006,2025-09-09
4,2025-09-10 00:00:00+07:00,2025-09-10T07:00:00+07:00,38.0,587,SKG007,2025-09-09

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-22.csv
🔹 Shape: (906, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-23 00:00:00+07:00,2025-09-23T07:00:00+07:00,4.4,1109530,ONE041,2025-09-22
1,2025-09-23 00:00:00+07:00,2025-09-23T07:00:00+07:00,21.0,696,TAKL,2025-09-22
2,2025-09-23 00:00:00+07:00,2025-09-23T07:00:00+07:00,0.0,789,KTLE,2025-09-22
3,2025-09-23 00:00:00+07:00,2025-09-23T07:00:00+07:00,0.0,740812,KWN003,2025-09-22
4,2025-09-23 00:00:00+07:00,2025-09-23T07:00:00+07:00,0.0,13888,SWR021,2025-09-22

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: rain_hii_20250902.csv
🔹 Shape: (1270, 3)
🔹 Columns: ['station_code', 'measure_datetime', 'value']
🔹 Data types:
station_code         object
measure_datetime     object
value               float64
dtype: object
🔹 Head:

  station_code measure_datetime  value
0         ACRU       2025-09-02    0.2
1       AIT001       2025-09-02    0.0
2       AIT002       2025-09-02    1.8
3       AIT005       2025-09-02    2.2
4       AIT008       2025-09-02    5.2

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-25.csv
🔹 Shape: (904, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-26 00:00:00+07:00,2025-09-26T07:00:00+07:00,0.4,740532,AIT002,2025-09-25
1,2025-09-26 00:00:00+07:00,2025-09-26T07:00:00+07:00,0.0,860,SLA002,2025-09-25
2,2025-09-26 00:00:00+07:00,2025-09-26T07:00:00+07:00,0.0,855,SLA003,2025-09-25
3,2025-09-26 00:00:00+07:00,2025-09-26T07:00:00+07:00,11.4,839,VLGE17,2025-09-25
4,2025-09-26 00:00:00+07:00,2025-09-26T07:00:00+07:00,23.4,608,VLGE15,2025-09-25

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-11.csv
🔹 Shape: (897, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-12 00:00:00+07:00,2025-09-12T07:00:00+07:00,0.2,1109592,ONE103,2025-09-11
1,2025-09-12 00:00:00+07:00,2025-09-12T07:00:00+07:00,0.0,1109569,ONE080,2025-09-11
2,2025-09-12 00:00:00+07:00,2025-09-12T07:00:00+07:00,0.0,172,RBPI,2025-09-11
3,2025-09-12 00:00:00+07:00,2025-09-12T07:00:00+07:00,0.0,888,STH001,2025-09-11
4,2025-09-12 00:00:00+07:00,2025-09-12T07:00:00+07:00,1.0,1601334,NaN,2025-09-11

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-19.csv
🔹 Shape: (897, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-20 00:00:00+07:00,2025-09-20T07:00:00+07:00,0.0,740812,KWN003,2025-09-19
1,2025-09-20 00:00:00+07:00,2025-09-20T07:00:00+07:00,7.0,517,NAMN,2025-09-19
2,2025-09-20 00:00:00+07:00,2025-09-20T07:00:00+07:00,0.0,852087,AIT001,2025-09-19
3,2025-09-20 00:00:00+07:00,2025-09-20T07:00:00+07:00,48.2,71,CPY006,2025-09-19
4,2025-09-20 00:00:00+07:00,2025-09-20T07:00:00+07:00,19.4,348,KON001,2025-09-19

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-30.csv
🔹 Shape: (913, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-01 00:00:00+07:00,2025-09-30T07:00:00+07:00,7.6,1373272,NaN,2025-09-30
1,2025-10-01 00:00:00+07:00,2025-09-30T07:00:00+07:00,3.6,1116457,GOT001,2025-09-30
2,2025-10-01 00:00:00+07:00,2025-09-30T07:00:00+07:00,5.4,537,CHR001,2025-09-30
3,2025-10-01 00:00:00+07:00,2025-09-30T07:00:00+07:00,7.0,1197836,CHR007,2025-09-30
4,2025-10-01 00:00:00+07:00,2025-09-30T07:00:00+07:00,0.0,743,KSKP,2025-09-30

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-08.csv
🔹 Shape: (895, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-09 00:00:00+07:00,2025-09-09T07:00:00+07:00,1.2,1109493,ONE004,2025-09-08
1,2025-09-09 00:00:00+07:00,2025-09-09T07:00:00+07:00,0.0,533,YOM001,2025-09-08
2,2025-09-09 00:00:00+07:00,2025-09-09T07:00:00+07:00,0.6,1109495,ONE006,2025-09-08
3,2025-09-09 00:00:00+07:00,2025-09-09T07:00:00+07:00,0.0,499,YOM003,2025-09-08
4,2025-09-09 00:00:00+07:00,2025-09-09T07:00:00+07:00,0.2,12480,TNG003,2025-09-08

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-16.csv
🔹 Shape: (893, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-17 00:00:00+07:00,2025-09-17T07:00:00+07:00,0.0,922,SAY002,2025-09-16
1,2025-09-17 00:00:00+07:00,2025-09-17T07:00:00+07:00,14.8,13883,SWR016,2025-09-16
2,2025-09-17 00:00:00+07:00,2025-09-17T07:00:00+07:00,13.8,13891,SWR024,2025-09-16
3,2025-09-17 00:00:00+07:00,2025-09-17T07:00:00+07:00,13.8,13869,SWR002,2025-09-16
4,2025-09-17 00:00:00+07:00,2025-09-17T07:00:00+07:00,32.2,13882,SWR015,2025-09-16

--------------------------------------------------------------------------------
📂 Folder: 2025-09
📄 File: HII_daily_rainfall_2025-09-10.csv
🔹 Shape: (900, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-11 00:00:00+07:00,2025-09-11T07:00:00+07:00,0.0,808,BYNU,2025-09-10
1,2025-09-11 00:00:00+07:00,2025-09-11T07:00:00+07:00,0.0,269,CHI011,2025-09-10
2,2025-09-11 00:00:00+07:00,2025-09-11T07:00:00+07:00,1.4,1091551,CHK002,2025-09-10
3,2025-09-11 00:00:00+07:00,2025-09-11T07:00:00+07:00,0.2,533,YOM001,2025-09-10
4,2025-09-11 00:00:00+07:00,2025-09-11T07:00:00+07:00,0.8,1082427,CHK001,2025-09-10

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-02.csv
🔹 Shape: (1055, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,1109576,ONE087,2025-12-02
1,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,135,VLGE03,2025-12-02
2,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,134,TRD004,2025-12-02
3,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,114,UTOG,2025-12-02
4,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,103,TB0004,2025-12-02

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-03.csv
🔹 Shape: (1055, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,10,BKK005,2025-12-03
1,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,1601338,NaN,2025-12-03
2,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,1601337,NaN,2025-12-03
3,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,1601336,NaN,2025-12-03
4,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,1601335,NaN,2025-12-03

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-09.csv
🔹 Shape: (1064, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-10 00:00:00+07:00,2025-12-09T07:00:00+07:00,0.0,707,KCWF,2025-12-09
1,2025-12-10 00:00:00+07:00,2025-12-09T07:00:00+07:00,0.0,757,BNPK,2025-12-09
2,2025-12-10 00:00:00+07:00,2025-12-09T07:00:00+07:00,0.0,13872,SWR005,2025-12-09
3,2025-12-10 00:00:00+07:00,2025-12-09T07:00:00+07:00,0.0,862,JBLG,2025-12-09
4,2025-12-10 00:00:00+07:00,2025-12-09T07:00:00+07:00,0.0,668,VLGE12,2025-12-09

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-04.csv
🔹 Shape: (1054, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-05 00:00:00+07:00,2025-12-04T07:00:00+07:00,0.0,525,WBYN,2025-12-04
1,2025-12-05 00:00:00+07:00,2025-12-04T07:00:00+07:00,0.0,478,NAN010,2025-12-04
2,2025-12-05 00:00:00+07:00,2025-12-04T07:00:00+07:00,0.0,744,TANA,2025-12-04
3,2025-12-05 00:00:00+07:00,2025-12-04T07:00:00+07:00,0.0,747,BKK019,2025-12-04
4,2025-12-05 00:00:00+07:00,2025-12-04T07:00:00+07:00,0.0,723,DNCM,2025-12-04

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-08.csv
🔹 Shape: (1059, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-09 00:00:00+07:00,2025-12-08T07:00:00+07:00,0.0,109,SWNG,2025-12-08
1,2025-12-09 00:00:00+07:00,2025-12-08T07:00:00+07:00,0.0,435369,TBR013,2025-12-08
2,2025-12-09 00:00:00+07:00,2025-12-08T07:00:00+07:00,0.0,625,KTKB,2025-12-08
3,2025-12-09 00:00:00+07:00,2025-12-08T07:00:00+07:00,0.0,832,BBHN,2025-12-08
4,2025-12-09 00:00:00+07:00,2025-12-08T07:00:00+07:00,0.0,48,CPY009,2025-12-08

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-11.csv
🔹 Shape: (1064, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-12 00:00:00+07:00,2025-12-11T07:00:00+07:00,0.0,175,NYK008,2025-12-11
1,2025-12-12 00:00:00+07:00,2025-12-11T07:00:00+07:00,1.0,83,CPY003,2025-12-11
2,2025-12-12 00:00:00+07:00,2025-12-11T07:00:00+07:00,19.0,859,SLA005,2025-12-11
3,2025-12-12 00:00:00+07:00,2025-12-11T07:00:00+07:00,0.0,1132567,ONE108,2025-12-11
4,2025-12-12 00:00:00+07:00,2025-12-11T07:00:00+07:00,0.0,281,MUN011,2025-12-11

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-10.csv
🔹 Shape: (1065, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-11 00:00:00+07:00,2025-12-10T07:00:00+07:00,0.0,385581,TBW014,2025-12-10
1,2025-12-11 00:00:00+07:00,2025-12-10T07:00:00+07:00,0.2,196,TON004,2025-12-10
2,2025-12-11 00:00:00+07:00,2025-12-10T07:00:00+07:00,0.0,925,BUKT,2025-12-10
3,2025-12-11 00:00:00+07:00,2025-12-10T07:00:00+07:00,0.0,343,BPIA,2025-12-10
4,2025-12-11 00:00:00+07:00,2025-12-10T07:00:00+07:00,0.0,1601330,NaN,2025-12-10

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-06.csv
🔹 Shape: (1053, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-07 00:00:00+07:00,2025-12-06T07:00:00+07:00,0.0,663,BRKM,2025-12-06
1,2025-12-07 00:00:00+07:00,2025-12-06T07:00:00+07:00,0.0,869,TNG001,2025-12-06
2,2025-12-07 00:00:00+07:00,2025-12-06T07:00:00+07:00,0.0,298,CHI001,2025-12-06
3,2025-12-07 00:00:00+07:00,2025-12-06T07:00:00+07:00,0.0,216,WEI142,2025-12-06
4,2025-12-07 00:00:00+07:00,2025-12-06T07:00:00+07:00,0.0,431,NTNG,2025-12-06

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-01.csv
🔹 Shape: (1054, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-02 00:00:00+07:00,2025-12-01T07:00:00+07:00,0.0,475,NAN014,2025-12-01
1,2025-12-02 00:00:00+07:00,2025-12-01T07:00:00+07:00,0.0,330,CHI005,2025-12-01
2,2025-12-02 00:00:00+07:00,2025-12-01T07:00:00+07:00,0.0,333,CHI006,2025-12-01
3,2025-12-02 00:00:00+07:00,2025-12-01T07:00:00+07:00,0.0,334,KUDN,2025-12-01
4,2025-12-02 00:00:00+07:00,2025-12-01T07:00:00+07:00,0.0,584,CPY002,2025-12-01

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-05.csv
🔹 Shape: (1055, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-06 00:00:00+07:00,2025-12-05T07:00:00+07:00,0.0,260,BTUD,2025-12-05
1,2025-12-06 00:00:00+07:00,2025-12-05T07:00:00+07:00,0.0,253,THAT,2025-12-05
2,2025-12-06 00:00:00+07:00,2025-12-05T07:00:00+07:00,0.0,369,SACS,2025-12-05
3,2025-12-06 00:00:00+07:00,2025-12-05T07:00:00+07:00,3.6,46,CPY013,2025-12-05
4,2025-12-06 00:00:00+07:00,2025-12-05T07:00:00+07:00,0.0,437,OMKI,2025-12-05

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-07.csv
🔹 Shape: (1057, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-08 00:00:00+07:00,2025-12-07T07:00:00+07:00,7.4,13898,SWR031,2025-12-07
1,2025-12-08 00:00:00+07:00,2025-12-07T07:00:00+07:00,0.0,215,BGRT,2025-12-07
2,2025-12-08 00:00:00+07:00,2025-12-07T07:00:00+07:00,0.0,567,PMPA,2025-12-07
3,2025-12-08 00:00:00+07:00,2025-12-07T07:00:00+07:00,0.0,625,KTKB,2025-12-07
4,2025-12-08 00:00:00+07:00,2025-12-07T07:00:00+07:00,0.0,438,WGHG,2025-12-07

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-29.csv
🔹 Shape: (1053, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-30 00:00:00+07:00,2025-12-29T07:00:00+07:00,0.0,142,BDCP,2025-12-29
1,2025-12-30 00:00:00+07:00,2025-12-29T07:00:00+07:00,0.0,859,SLA005,2025-12-29
2,2025-12-30 00:00:00+07:00,2025-12-29T07:00:00+07:00,0.0,706,RAJ003,2025-12-29
3,2025-12-30 00:00:00+07:00,2025-12-29T07:00:00+07:00,0.0,1601379,NaN,2025-12-29
4,2025-12-30 00:00:00+07:00,2025-12-29T07:00:00+07:00,0.0,1601370,NaN,2025-12-29

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-14.csv
🔹 Shape: (1060, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-15 00:00:00+07:00,2025-12-14T07:00:00+07:00,0.0,278,TKPP,2025-12-14
1,2025-12-15 00:00:00+07:00,2025-12-14T07:00:00+07:00,0.0,781,BSPN,2025-12-14
2,2025-12-15 00:00:00+07:00,2025-12-14T07:00:00+07:00,26.8,797,KKHA,2025-12-14
3,2025-12-15 00:00:00+07:00,2025-12-14T07:00:00+07:00,0.0,783,WWST,2025-12-14
4,2025-12-15 00:00:00+07:00,2025-12-14T07:00:00+07:00,0.0,435372,TBR016,2025-12-14

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-27.csv
🔹 Shape: (1051, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-28 00:00:00+07:00,2025-12-27T07:00:00+07:00,0.0,407,DTAN,2025-12-27
1,2025-12-28 00:00:00+07:00,2025-12-27T07:00:00+07:00,0.0,130,MMNY,2025-12-27
2,2025-12-28 00:00:00+07:00,2025-12-27T07:00:00+07:00,0.0,698,WCBR,2025-12-27
3,2025-12-28 00:00:00+07:00,2025-12-27T07:00:00+07:00,0.0,420,MNDM,2025-12-27
4,2025-12-28 00:00:00+07:00,2025-12-27T07:00:00+07:00,0.0,453,MMMO,2025-12-27

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-28.csv
🔹 Shape: (1053, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-29 00:00:00+07:00,2025-12-28T07:00:00+07:00,0.0,728,KKWF,2025-12-28
1,2025-12-29 00:00:00+07:00,2025-12-28T07:00:00+07:00,0.0,1109560,ONE071,2025-12-28
2,2025-12-29 00:00:00+07:00,2025-12-28T07:00:00+07:00,3.0,884,STH020,2025-12-28
3,2025-12-29 00:00:00+07:00,2025-12-28T07:00:00+07:00,0.0,301,TEPT,2025-12-28
4,2025-12-29 00:00:00+07:00,2025-12-28T07:00:00+07:00,0.0,462,TETN,2025-12-28

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-15.csv
🔹 Shape: (1057, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-16 00:00:00+07:00,2025-12-15T07:00:00+07:00,0.0,444,DOCI,2025-12-15
1,2025-12-16 00:00:00+07:00,2025-12-15T07:00:00+07:00,0.0,243,KNDG,2025-12-15
2,2025-12-16 00:00:00+07:00,2025-12-15T07:00:00+07:00,0.0,712,VLGE30,2025-12-15
3,2025-12-16 00:00:00+07:00,2025-12-15T07:00:00+07:00,0.6,901,PAT002,2025-12-15
4,2025-12-16 00:00:00+07:00,2025-12-15T07:00:00+07:00,0.0,225,WNKH,2025-12-15

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-24.csv
🔹 Shape: (1055, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-25 00:00:00+07:00,2025-12-24T07:00:00+07:00,0.0,1109552,ONE063,2025-12-24
1,2025-12-25 00:00:00+07:00,2025-12-24T07:00:00+07:00,0.0,1109510,ONE021,2025-12-24
2,2025-12-25 00:00:00+07:00,2025-12-24T07:00:00+07:00,1.0,915,STH018,2025-12-24
3,2025-12-25 00:00:00+07:00,2025-12-24T07:00:00+07:00,0.0,115,RAY001,2025-12-24
4,2025-12-25 00:00:00+07:00,2025-12-24T07:00:00+07:00,0.0,635,VLGE45,2025-12-24

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-16.csv
🔹 Shape: (1052, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-17 00:00:00+07:00,2025-12-16T07:00:00+07:00,0.0,575567,BKC003,2025-12-16
1,2025-12-17 00:00:00+07:00,2025-12-16T07:00:00+07:00,0.0,215,BGRT,2025-12-16
2,2025-12-17 00:00:00+07:00,2025-12-16T07:00:00+07:00,0.0,494,DCCT,2025-12-16
3,2025-12-17 00:00:00+07:00,2025-12-16T07:00:00+07:00,0.0,881,STH015,2025-12-16
4,2025-12-17 00:00:00+07:00,2025-12-16T07:00:00+07:00,0.0,79,THA001,2025-12-16

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-18.csv
🔹 Shape: (1050, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-19 00:00:00+07:00,2025-12-18T07:00:00+07:00,0.0,1109494,ONE005,2025-12-18
1,2025-12-19 00:00:00+07:00,2025-12-18T07:00:00+07:00,0.0,479235,TBW027,2025-12-18
2,2025-12-19 00:00:00+07:00,2025-12-18T07:00:00+07:00,0.0,72,PCHI,2025-12-18
3,2025-12-19 00:00:00+07:00,2025-12-18T07:00:00+07:00,0.0,660,NKTI,2025-12-18
4,2025-12-19 00:00:00+07:00,2025-12-18T07:00:00+07:00,0.0,1109543,ONE054,2025-12-18

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-12.csv
🔹 Shape: (1059, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-13 00:00:00+07:00,2025-12-12T07:00:00+07:00,0.0,221,TLPC,2025-12-12
1,2025-12-13 00:00:00+07:00,2025-12-12T07:00:00+07:00,0.0,431,NTNG,2025-12-12
2,2025-12-13 00:00:00+07:00,2025-12-12T07:00:00+07:00,0.2,397,BAKI,2025-12-12
3,2025-12-13 00:00:00+07:00,2025-12-12T07:00:00+07:00,0.0,213,BSUM,2025-12-12
4,2025-12-13 00:00:00+07:00,2025-12-12T07:00:00+07:00,0.6,536,RIKK,2025-12-12

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-30.csv
🔹 Shape: (1048, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-31 00:00:00+07:00,2025-12-30T07:00:00+07:00,2.4,1109513,ONE024,2025-12-30
1,2025-12-31 00:00:00+07:00,2025-12-30T07:00:00+07:00,0.0,727,DDSO,2025-12-30
2,2025-12-31 00:00:00+07:00,2025-12-30T07:00:00+07:00,0.0,119,BNGR,2025-12-30
3,2025-12-31 00:00:00+07:00,2025-12-30T07:00:00+07:00,0.0,122,PNRN,2025-12-30
4,2025-12-31 00:00:00+07:00,2025-12-30T07:00:00+07:00,0.0,1601358,NaN,2025-12-30

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-17.csv
🔹 Shape: (1058, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-18 00:00:00+07:00,2025-12-17T07:00:00+07:00,0.0,940,VLGE34,2025-12-17
1,2025-12-18 00:00:00+07:00,2025-12-17T07:00:00+07:00,0.0,581,TTKO,2025-12-17
2,2025-12-18 00:00:00+07:00,2025-12-17T07:00:00+07:00,0.0,342,KON002,2025-12-17
3,2025-12-18 00:00:00+07:00,2025-12-17T07:00:00+07:00,1.6,865,TNG002,2025-12-17
4,2025-12-18 00:00:00+07:00,2025-12-17T07:00:00+07:00,0.0,1677420,NaN,2025-12-17

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-19.csv
🔹 Shape: (1052, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-20 00:00:00+07:00,2025-12-19T07:00:00+07:00,0.0,400,PPAN,2025-12-19
1,2025-12-20 00:00:00+07:00,2025-12-19T07:00:00+07:00,0.0,1109544,ONE055,2025-12-19
2,2025-12-20 00:00:00+07:00,2025-12-19T07:00:00+07:00,0.6,923,STH019,2025-12-19
3,2025-12-20 00:00:00+07:00,2025-12-19T07:00:00+07:00,0.0,555,WGKN,2025-12-19
4,2025-12-20 00:00:00+07:00,2025-12-19T07:00:00+07:00,0.0,145,BGBO,2025-12-19

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-20.csv
🔹 Shape: (1052, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-21 00:00:00+07:00,2025-12-20T07:00:00+07:00,0.0,345,POCE,2025-12-20
1,2025-12-21 00:00:00+07:00,2025-12-20T07:00:00+07:00,0.0,762,CHAM,2025-12-20
2,2025-12-21 00:00:00+07:00,2025-12-20T07:00:00+07:00,0.0,1109494,ONE005,2025-12-20
3,2025-12-21 00:00:00+07:00,2025-12-20T07:00:00+07:00,0.0,286,TSUD,2025-12-20
4,2025-12-21 00:00:00+07:00,2025-12-20T07:00:00+07:00,0.0,436,DITO,2025-12-20

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-22.csv
🔹 Shape: (1052, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-23 00:00:00+07:00,2025-12-22T07:00:00+07:00,0.0,1601368,NaN,2025-12-22
1,2025-12-23 00:00:00+07:00,2025-12-22T07:00:00+07:00,0.0,526,PYO001,2025-12-22
2,2025-12-23 00:00:00+07:00,2025-12-22T07:00:00+07:00,0.0,57,CPY017,2025-12-22
3,2025-12-23 00:00:00+07:00,2025-12-22T07:00:00+07:00,0.0,1601362,NaN,2025-12-22
4,2025-12-23 00:00:00+07:00,2025-12-22T07:00:00+07:00,0.0,1109548,ONE059,2025-12-22

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-23.csv
🔹 Shape: (1050, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,435372,TBR016,2025-12-23
1,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,1109543,ONE054,2025-12-23
2,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,479220,TBR021,2025-12-23
3,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,865,TNG002,2025-12-23
4,2025-12-24 00:00:00+07:00,2025-12-23T07:00:00+07:00,0.0,12481,STU002,2025-12-23

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-31.csv
🔹 Shape: (1050, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2026-01-01 00:00:00+07:00,2025-12-31T07:00:00+07:00,0.0,1601358,NaN,2025-12-31
1,2026-01-01 00:00:00+07:00,2025-12-31T07:00:00+07:00,0.0,395,SKM001,2025-12-31
2,2026-01-01 00:00:00+07:00,2025-12-31T07:00:00+07:00,0.0,721,DGSL,2025-12-31
3,2026-01-01 00:00:00+07:00,2025-12-31T07:00:00+07:00,0.0,855,SLA003,2025-12-31
4,2026-01-01 00:00:00+07:00,2025-12-31T07:00:00+07:00,0.0,434,CHM002,2025-12-31

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-26.csv
🔹 Shape: (1050, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-27 00:00:00+07:00,2025-12-26T07:00:00+07:00,33.0,871,TKRA,2025-12-26
1,2025-12-27 00:00:00+07:00,2025-12-26T07:00:00+07:00,0.0,1109592,ONE103,2025-12-26
2,2025-12-27 00:00:00+07:00,2025-12-26T07:00:00+07:00,0.0,709,RAJ002,2025-12-26
3,2025-12-27 00:00:00+07:00,2025-12-26T07:00:00+07:00,0.0,1601380,NaN,2025-12-26
4,2025-12-27 00:00:00+07:00,2025-12-26T07:00:00+07:00,0.0,1106450,TCP004,2025-12-26

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-25.csv
🔹 Shape: (1050, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,581,TTKO,2025-12-25
1,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,638,PIN002,2025-12-25
2,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,1106450,TCP004,2025-12-25
3,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,1645475,NaN,2025-12-25
4,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,582,PSLI,2025-12-25

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-21.csv
🔹 Shape: (1049, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-22 00:00:00+07:00,2025-12-21T07:00:00+07:00,0.0,654,SNKO,2025-12-21
1,2025-12-22 00:00:00+07:00,2025-12-21T07:00:00+07:00,0.0,478,NAN010,2025-12-21
2,2025-12-22 00:00:00+07:00,2025-12-21T07:00:00+07:00,0.0,1198082,NAN016,2025-12-21
3,2025-12-22 00:00:00+07:00,2025-12-21T07:00:00+07:00,0.0,350,PHKD,2025-12-21
4,2025-12-22 00:00:00+07:00,2025-12-21T07:00:00+07:00,0.0,543,PANC,2025-12-21

--------------------------------------------------------------------------------
📂 Folder: 2025-12
📄 File: HII_daily_rainfall_2025-12-13.csv
🔹 Shape: (1063, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.2,828,TPI007,2025-12-13
1,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,11.0,841,CMP002,2025-12-13
2,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,26.0,344,NASW,2025-12-13
3,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,1109589,ONE100,2025-12-13
4,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,22.0,662,CTKN,2025-12-13

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-07.csv
🔹 Shape: (1029, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,0.0,455701,ONWR02,2025-11-07
1,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,11.6,1109584,ONE095,2025-11-07
2,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,15.4,618,SKG005,2025-11-07
3,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,26.0,278,TKPP,2025-11-07
4,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,0.0,1109580,ONE091,2025-11-07

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-24.csv
🔹 Shape: (1045, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-25 00:00:00+07:00,2025-11-24T07:00:00+07:00,13.6,792,NKO002,2025-11-24
1,2025-11-25 00:00:00+07:00,2025-11-24T07:00:00+07:00,0.0,1109539,ONE050,2025-11-24
2,2025-11-25 00:00:00+07:00,2025-11-24T07:00:00+07:00,4.8,1109538,ONE049,2025-11-24
3,2025-11-25 00:00:00+07:00,2025-11-24T07:00:00+07:00,0.0,416,DSKT,2025-11-24
4,2025-11-25 00:00:00+07:00,2025-11-24T07:00:00+07:00,0.0,607,KPPT,2025-11-24

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-27.csv
🔹 Shape: (1039, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-28 00:00:00+07:00,2025-11-27T07:00:00+07:00,0.0,140,HTTM,2025-11-27
1,2025-11-28 00:00:00+07:00,2025-11-27T07:00:00+07:00,0.0,246,NANP,2025-11-27
2,2025-11-28 00:00:00+07:00,2025-11-27T07:00:00+07:00,0.0,578,TAKI,2025-11-27
3,2025-11-28 00:00:00+07:00,2025-11-27T07:00:00+07:00,0.0,846,SVI002,2025-11-27
4,2025-11-28 00:00:00+07:00,2025-11-27T07:00:00+07:00,0.0,138,TRD002,2025-11-27

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-15.csv
🔹 Shape: (1047, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-16 00:00:00+07:00,2025-11-15T07:00:00+07:00,0.0,479216,TBR017,2025-11-15
1,2025-11-16 00:00:00+07:00,2025-11-15T07:00:00+07:00,0.0,780,BSVT,2025-11-15
2,2025-11-16 00:00:00+07:00,2025-11-15T07:00:00+07:00,0.0,588,TKFA,2025-11-15
3,2025-11-16 00:00:00+07:00,2025-11-15T07:00:00+07:00,0.0,194,KOKN,2025-11-15
4,2025-11-16 00:00:00+07:00,2025-11-15T07:00:00+07:00,0.0,937,PNCR,2025-11-15

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-21.csv
🔹 Shape: (1047, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-22 00:00:00+07:00,2025-11-21T07:00:00+07:00,0.0,657,NAN012,2025-11-21
1,2025-11-22 00:00:00+07:00,2025-11-21T07:00:00+07:00,0.0,678,WTLG,2025-11-21
2,2025-11-22 00:00:00+07:00,2025-11-21T07:00:00+07:00,0.0,326,PHON,2025-11-21
3,2025-11-22 00:00:00+07:00,2025-11-21T07:00:00+07:00,0.0,492353,ATG092,2025-11-21
4,2025-11-22 00:00:00+07:00,2025-11-21T07:00:00+07:00,0.0,447,THCG,2025-11-21

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-09.csv
🔹 Shape: (1031, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-10 00:00:00+07:00,2025-11-09T07:00:00+07:00,0.0,814,KOSK,2025-11-09
1,2025-11-10 00:00:00+07:00,2025-11-09T07:00:00+07:00,19.2,941,VLGE06,2025-11-09
2,2025-11-10 00:00:00+07:00,2025-11-09T07:00:00+07:00,1.0,13886,SWR019,2025-11-09
3,2025-11-10 00:00:00+07:00,2025-11-09T07:00:00+07:00,0.0,219,VLGE01,2025-11-09
4,2025-11-10 00:00:00+07:00,2025-11-09T07:00:00+07:00,0.0,479236,TBW028,2025-11-09

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-01.csv
🔹 Shape: (1009, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-02 00:00:00+07:00,2025-11-01T07:00:00+07:00,1.6,245,MUN009,2025-11-01
1,2025-11-02 00:00:00+07:00,2025-11-01T07:00:00+07:00,72.0,12477,PRN002,2025-11-01
2,2025-11-02 00:00:00+07:00,2025-11-01T07:00:00+07:00,0.0,850,JNA002,2025-11-01
3,2025-11-02 00:00:00+07:00,2025-11-01T07:00:00+07:00,41.6,782,MPBR,2025-11-01
4,2025-11-02 00:00:00+07:00,2025-11-01T07:00:00+07:00,61.2,575572,BKC008,2025-11-01

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-25.csv
🔹 Shape: (1037, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-26 00:00:00+07:00,2025-11-25T07:00:00+07:00,39.2,799,CHNA,2025-11-25
1,2025-11-26 00:00:00+07:00,2025-11-25T07:00:00+07:00,32.0,905,PAT001,2025-11-25
2,2025-11-26 00:00:00+07:00,2025-11-25T07:00:00+07:00,0.0,1601365,NaN,2025-11-25
3,2025-11-26 00:00:00+07:00,2025-11-25T07:00:00+07:00,0.0,492357,ATG121,2025-11-25
4,2025-11-26 00:00:00+07:00,2025-11-25T07:00:00+07:00,0.0,402,BNKE,2025-11-25

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-05.csv
🔹 Shape: (1023, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-06 00:00:00+07:00,2025-11-05T07:00:00+07:00,0.0,920,STH005,2025-11-05
1,2025-11-06 00:00:00+07:00,2025-11-05T07:00:00+07:00,1.6,881,STH015,2025-11-05
2,2025-11-06 00:00:00+07:00,2025-11-05T07:00:00+07:00,0.0,729,NAPJ,2025-11-05
3,2025-11-06 00:00:00+07:00,2025-11-05T07:00:00+07:00,0.0,1198626,TRD005,2025-11-05
4,2025-11-06 00:00:00+07:00,2025-11-05T07:00:00+07:00,0.0,279,BHRA,2025-11-05

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-20.csv
🔹 Shape: (1048, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-21 00:00:00+07:00,2025-11-20T07:00:00+07:00,0.0,1109579,ONE090,2025-11-20
1,2025-11-21 00:00:00+07:00,2025-11-20T07:00:00+07:00,0.0,83,CPY003,2025-11-20
2,2025-11-21 00:00:00+07:00,2025-11-20T07:00:00+07:00,0.0,13880,SWR013,2025-11-20
3,2025-11-21 00:00:00+07:00,2025-11-20T07:00:00+07:00,0.0,716,KOSR,2025-11-20
4,2025-11-21 00:00:00+07:00,2025-11-20T07:00:00+07:00,0.0,466,BNAN,2025-11-20

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-26.csv
🔹 Shape: (1045, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-27 00:00:00+07:00,2025-11-26T07:00:00+07:00,44.2,880,STH012,2025-11-26
1,2025-11-27 00:00:00+07:00,2025-11-26T07:00:00+07:00,0.0,400,PPAN,2025-11-26
2,2025-11-27 00:00:00+07:00,2025-11-26T07:00:00+07:00,0.0,824,TPI003,2025-11-26
3,2025-11-27 00:00:00+07:00,2025-11-26T07:00:00+07:00,0.0,1373690,NaN,2025-11-26
4,2025-11-27 00:00:00+07:00,2025-11-26T07:00:00+07:00,0.0,202,BUGN,2025-11-26

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-02.csv
🔹 Shape: (1005, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-03 00:00:00+07:00,2025-11-02T07:00:00+07:00,40.4,492340,ATG021,2025-11-02
1,2025-11-03 00:00:00+07:00,2025-11-02T07:00:00+07:00,0.0,394,BTHO,2025-11-02
2,2025-11-03 00:00:00+07:00,2025-11-02T07:00:00+07:00,48.2,1601376,NaN,2025-11-02
3,2025-11-03 00:00:00+07:00,2025-11-02T07:00:00+07:00,4.2,1106450,TCP004,2025-11-02
4,2025-11-03 00:00:00+07:00,2025-11-02T07:00:00+07:00,0.2,1601330,NaN,2025-11-02

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-22.csv
🔹 Shape: (1046, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,492367,ATG171,2025-11-22
1,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,119.6,901,PAT002,2025-11-22
2,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,278,TKPP,2025-11-22
3,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,479234,TBW026,2025-11-22
4,2025-11-23 00:00:00+07:00,2025-11-22T07:00:00+07:00,0.0,378,VLGE39,2025-11-22

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-19.csv
🔹 Shape: (1049, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-20 00:00:00+07:00,2025-11-19T07:00:00+07:00,0.0,482,NAN004,2025-11-19
1,2025-11-20 00:00:00+07:00,2025-11-19T07:00:00+07:00,0.0,162,PRC001,2025-11-19
2,2025-11-20 00:00:00+07:00,2025-11-19T07:00:00+07:00,0.0,582,PSLI,2025-11-19
3,2025-11-20 00:00:00+07:00,2025-11-19T07:00:00+07:00,4.2,528,CHUN,2025-11-19
4,2025-11-20 00:00:00+07:00,2025-11-19T07:00:00+07:00,0.0,721,DGSL,2025-11-19

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-28.csv
🔹 Shape: (1030, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-29 00:00:00+07:00,2025-11-28T07:00:00+07:00,0.0,797,KKHA,2025-11-28
1,2025-11-29 00:00:00+07:00,2025-11-28T07:00:00+07:00,0.0,821,TPI005,2025-11-28
2,2025-11-29 00:00:00+07:00,2025-11-28T07:00:00+07:00,0.0,665,VLGE13,2025-11-28
3,2025-11-29 00:00:00+07:00,2025-11-28T07:00:00+07:00,0.0,1117429,PYO002,2025-11-28
4,2025-11-29 00:00:00+07:00,2025-11-28T07:00:00+07:00,0.0,54,CPY016,2025-11-28

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-06.csv
🔹 Shape: (1029, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-07 00:00:00+07:00,2025-11-06T07:00:00+07:00,0.0,432,KUAM,2025-11-06
1,2025-11-07 00:00:00+07:00,2025-11-06T07:00:00+07:00,0.6,1109556,ONE067,2025-11-06
2,2025-11-07 00:00:00+07:00,2025-11-06T07:00:00+07:00,0.0,492364,ATG152,2025-11-06
3,2025-11-07 00:00:00+07:00,2025-11-06T07:00:00+07:00,2.6,1109512,ONE023,2025-11-06
4,2025-11-07 00:00:00+07:00,2025-11-06T07:00:00+07:00,0.0,913,KABG,2025-11-06

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-16.csv
🔹 Shape: (1043, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-17 00:00:00+07:00,2025-11-16T07:00:00+07:00,0.0,420,MNDM,2025-11-16
1,2025-11-17 00:00:00+07:00,2025-11-16T07:00:00+07:00,0.0,674,WGTG,2025-11-16
2,2025-11-17 00:00:00+07:00,2025-11-16T07:00:00+07:00,0.0,914,STH008,2025-11-16
3,2025-11-17 00:00:00+07:00,2025-11-16T07:00:00+07:00,0.0,489,YOM010,2025-11-16
4,2025-11-17 00:00:00+07:00,2025-11-16T07:00:00+07:00,0.0,1109508,ONE019,2025-11-16

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-13.csv
🔹 Shape: (1042, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-14 00:00:00+07:00,2025-11-13T07:00:00+07:00,0.0,555,WGKN,2025-11-13
1,2025-11-14 00:00:00+07:00,2025-11-13T07:00:00+07:00,0.0,1109522,ONE033,2025-11-13
2,2025-11-14 00:00:00+07:00,2025-11-13T07:00:00+07:00,0.0,494,DCCT,2025-11-13
3,2025-11-14 00:00:00+07:00,2025-11-13T07:00:00+07:00,13.0,743,KSKP,2025-11-13
4,2025-11-14 00:00:00+07:00,2025-11-13T07:00:00+07:00,2.8,630,WAN001,2025-11-13

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-30.csv
🔹 Shape: (1050, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-01 00:00:00+07:00,2025-11-30T07:00:00+07:00,0.0,12483,NKO003,2025-11-30
1,2025-12-01 00:00:00+07:00,2025-11-30T07:00:00+07:00,0.0,12485,NKO004,2025-11-30
2,2025-12-01 00:00:00+07:00,2025-11-30T07:00:00+07:00,0.0,13829,SWR001,2025-11-30
3,2025-12-01 00:00:00+07:00,2025-11-30T07:00:00+07:00,0.0,13869,SWR002,2025-11-30
4,2025-12-01 00:00:00+07:00,2025-11-30T07:00:00+07:00,0.0,13870,SWR003,2025-11-30

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-10.csv
🔹 Shape: (1034, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-11 00:00:00+07:00,2025-11-10T07:00:00+07:00,0.0,119,BNGR,2025-11-10
1,2025-11-11 00:00:00+07:00,2025-11-10T07:00:00+07:00,0.0,379,VLGE43,2025-11-10
2,2025-11-11 00:00:00+07:00,2025-11-10T07:00:00+07:00,0.0,214,NGCH,2025-11-10
3,2025-11-11 00:00:00+07:00,2025-11-10T07:00:00+07:00,1.8,719,HKTG,2025-11-10
4,2025-11-11 00:00:00+07:00,2025-11-10T07:00:00+07:00,11.6,901,PAT002,2025-11-10

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-17.csv
🔹 Shape: (1042, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-18 00:00:00+07:00,2025-11-17T07:00:00+07:00,0.0,1109543,ONE054,2025-11-17
1,2025-11-18 00:00:00+07:00,2025-11-17T07:00:00+07:00,0.0,492365,ATG161,2025-11-17
2,2025-11-18 00:00:00+07:00,2025-11-17T07:00:00+07:00,0.0,492358,ATG122,2025-11-17
3,2025-11-18 00:00:00+07:00,2025-11-17T07:00:00+07:00,3.8,814,KOSK,2025-11-17
4,2025-11-18 00:00:00+07:00,2025-11-17T07:00:00+07:00,21.6,635,VLGE45,2025-11-17

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-03.csv
🔹 Shape: (1012, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-04 00:00:00+07:00,2025-11-03T07:00:00+07:00,10.8,1109596,ONE107,2025-11-03
1,2025-11-04 00:00:00+07:00,2025-11-03T07:00:00+07:00,13.6,602,NKYG,2025-11-03
2,2025-11-04 00:00:00+07:00,2025-11-03T07:00:00+07:00,0.2,1106450,TCP004,2025-11-03
3,2025-11-04 00:00:00+07:00,2025-11-03T07:00:00+07:00,0.0,377,BMOD,2025-11-03
4,2025-11-04 00:00:00+07:00,2025-11-03T07:00:00+07:00,0.2,1109537,ONE048,2025-11-03

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-11.csv
🔹 Shape: (1035, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-12 00:00:00+07:00,2025-11-11T07:00:00+07:00,0.0,782,MPBR,2025-11-11
1,2025-11-12 00:00:00+07:00,2025-11-11T07:00:00+07:00,0.0,784,PRN001,2025-11-11
2,2025-11-12 00:00:00+07:00,2025-11-11T07:00:00+07:00,0.0,740537,AIT008,2025-11-11
3,2025-11-12 00:00:00+07:00,2025-11-11T07:00:00+07:00,0.0,1601374,NaN,2025-11-11
4,2025-11-12 00:00:00+07:00,2025-11-11T07:00:00+07:00,0.0,675,NAN013,2025-11-11

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-14.csv
🔹 Shape: (1048, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-15 00:00:00+07:00,2025-11-14T07:00:00+07:00,2.4,1085211,SKN003,2025-11-14
1,2025-11-15 00:00:00+07:00,2025-11-14T07:00:00+07:00,0.0,87,WTSG,2025-11-14
2,2025-11-15 00:00:00+07:00,2025-11-14T07:00:00+07:00,0.0,1601329,NaN,2025-11-14
3,2025-11-15 00:00:00+07:00,2025-11-14T07:00:00+07:00,0.0,672,WTBT,2025-11-14
4,2025-11-15 00:00:00+07:00,2025-11-14T07:00:00+07:00,0.0,111,NGSC,2025-11-14

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-29.csv
🔹 Shape: (1041, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-30 00:00:00+07:00,2025-11-29T07:00:00+07:00,0.0,458737,VLGE50,2025-11-29
1,2025-11-30 00:00:00+07:00,2025-11-29T07:00:00+07:00,0.0,1109491,ONE002,2025-11-29
2,2025-11-30 00:00:00+07:00,2025-11-29T07:00:00+07:00,0.0,1109577,ONE088,2025-11-29
3,2025-11-30 00:00:00+07:00,2025-11-29T07:00:00+07:00,0.0,1645475,NaN,2025-11-29
4,2025-11-30 00:00:00+07:00,2025-11-29T07:00:00+07:00,0.0,1512927,NaN,2025-11-29

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-08.csv
🔹 Shape: (1034, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-09 00:00:00+07:00,2025-11-08T07:00:00+07:00,22.6,481,PICI,2025-11-08
1,2025-11-09 00:00:00+07:00,2025-11-08T07:00:00+07:00,0.8,889,STH029,2025-11-08
2,2025-11-09 00:00:00+07:00,2025-11-08T07:00:00+07:00,29.2,1601328,NaN,2025-11-08
3,2025-11-09 00:00:00+07:00,2025-11-08T07:00:00+07:00,0.0,130,MMNY,2025-11-08
4,2025-11-09 00:00:00+07:00,2025-11-08T07:00:00+07:00,6.0,661,KWN001,2025-11-08

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-18.csv
🔹 Shape: (1042, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-19 00:00:00+07:00,2025-11-18T07:00:00+07:00,0.0,1109559,ONE070,2025-11-18
1,2025-11-19 00:00:00+07:00,2025-11-18T07:00:00+07:00,0.0,1109522,ONE033,2025-11-18
2,2025-11-19 00:00:00+07:00,2025-11-18T07:00:00+07:00,0.0,1601327,NaN,2025-11-18
3,2025-11-19 00:00:00+07:00,2025-11-18T07:00:00+07:00,0.2,229,WEI132,2025-11-18
4,2025-11-19 00:00:00+07:00,2025-11-18T07:00:00+07:00,0.0,387,BBUA,2025-11-18

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-23.csv
🔹 Shape: (1048, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-24 00:00:00+07:00,2025-11-23T07:00:00+07:00,3.4,869,TNG001,2025-11-23
1,2025-11-24 00:00:00+07:00,2025-11-23T07:00:00+07:00,0.0,322,WEI041,2025-11-23
2,2025-11-24 00:00:00+07:00,2025-11-23T07:00:00+07:00,0.0,1677418,NaN,2025-11-23
3,2025-11-24 00:00:00+07:00,2025-11-23T07:00:00+07:00,0.0,471584,HDA005,2025-11-23
4,2025-11-24 00:00:00+07:00,2025-11-23T07:00:00+07:00,19.2,12475,TNG004,2025-11-23

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-04.csv
🔹 Shape: (1018, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-05 00:00:00+07:00,2025-11-04T07:00:00+07:00,0.4,848,SYKP,2025-11-04
1,2025-11-05 00:00:00+07:00,2025-11-04T07:00:00+07:00,1.2,276,NYUN,2025-11-04
2,2025-11-05 00:00:00+07:00,2025-11-04T07:00:00+07:00,0.0,164,WTCH,2025-11-04
3,2025-11-05 00:00:00+07:00,2025-11-04T07:00:00+07:00,0.2,62,LNR1,2025-11-04
4,2025-11-05 00:00:00+07:00,2025-11-04T07:00:00+07:00,0.0,12474,STU003,2025-11-04

--------------------------------------------------------------------------------
📂 Folder: 2025-11
📄 File: HII_daily_rainfall_2025-11-12.csv
🔹 Shape: (1038, 6)
🔹 Columns: ['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime']
🔹 Data types:
rainfall_datetime          object
rainfall_datetime_calc     object
rainfall_value            float64
tele_station_id             int64
tele_station_oldcode       object
measure_datetime           object
dtype: object
🔹 Head:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-13 00:00:00+07:00,2025-11-12T07:00:00+07:00,5.4,749,VLGE20,2025-11-12
1,2025-11-13 00:00:00+07:00,2025-11-12T07:00:00+07:00,0.2,1198760,YOM014,2025-11-12
2,2025-11-13 00:00:00+07:00,2025-11-12T07:00:00+07:00,0.0,21,BKK017,2025-11-12
3,2025-11-13 00:00:00+07:00,2025-11-12T07:00:00+07:00,0.2,838,HJRN1,2025-11-12
4,2025-11-13 00:00:00+07:00,2025-11-12T07:00:00+07:00,0.0,445,BNHG,2025-11-12

--------------------------------------------------------------------------------

##รวมแต่ละเดือน

In [53]:
dfs = []
target_month07 = '2025-07'

for dirpath, dirnames, filenames in os.walk(root_directory):
    # ตรวจสอบว่าเส้นทางโฟลเดอร์ปัจจุบันมี target_month (เช่น '2025-07') อยู่หรือไม่
    if target_month07 in dirpath:   # ← เงื่อนไขคัดเลือก
        for filename in filenames:
            # ตรวจสอบว่าไฟล์เป็น CSV และไม่จำเป็นต้องมีคำว่า 'input' ในชื่อไฟล์อีกต่อไป
            if filename.endswith('.csv'): # เงื่อนไขถูกแก้ไข
                file_path = os.path.join(dirpath, filename)
                try:
                    df = pd.read_csv(file_path)
                    df['source_folder'] = os.path.basename(dirpath)
                    df['source_file'] = filename
                    dfs.append(df)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

# รวม DataFrame ทั้งหมด หากมี DataFrame อยู่ในลิสต์ dfs
if dfs:
    final_df07 = pd.concat(dfs, ignore_index=True)
    print(f"Successfully concatenated {len(dfs)} CSV files for {target_month07}.")
    print(final_df07.head())
else:
    final_df07 = pd.DataFrame()
    print(f"No CSV files found for {target_month07} that match the criteria, or an error occurred.")

Successfully concatenated 31 CSV files for 2025-07.
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-07-10 00:00:00+07:00  2025-07-10T07:00:00+07:00             0.0
1  2025-07-10 00:00:00+07:00  2025-07-10T07:00:00+07:00             0.0
2  2025-07-10 00:00:00+07:00  2025-07-10T07:00:00+07:00            27.8
3  2025-07-10 00:00:00+07:00  2025-07-10T07:00:00+07:00             0.0
4  2025-07-10 00:00:00+07:00  2025-07-10T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime source_folder  \
0              306                 BJIG       2025-07-09       2025-07
1              466                 BNAN       2025-07-09       2025-07
2              139                 BLKO       2025-07-09       2025-07
3              277                 BNAK       2025-07-09       2025-07
4              156               BPK004       2025-07-09       2025-07

                         source_file
0  HII_daily_rainfall_2025-07-09.csv
1  HII_daily_rainfall_2025-07-09.csv
2  HII_daily_rainfall_2025-07-09.csv
3  HII_daily_rainfall_2025-07-09.csv
4  HII_daily_rainfall_2025-07-09.csv

In [54]:
final_df07.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,source_folder,source_file
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306,BJIG,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466,BNAN,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139,BLKO,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277,BNAK,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156,BPK004,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv

In [55]:
dfs_08 = []
target_month08 = '2025-08'

for dirpath, dirnames, filenames in os.walk(root_directory):
    if target_month08 in dirpath:
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(dirpath, filename)
                try:
                    df_temp = pd.read_csv(file_path)
                    df_temp['source_folder'] = os.path.basename(dirpath)
                    df_temp['source_file'] = filename
                    dfs_08.append(df_temp)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

if dfs_08:
    final_df08 = pd.concat(dfs_08, ignore_index=True)
    print(f"Successfully concatenated {len(dfs_08)} CSV files for {target_month08}.")
    print(final_df08.head())
else:
    final_df08 = pd.DataFrame()
    print(f"No CSV files found for {target_month08} that match the criteria, or an error occurred.")

Successfully concatenated 32 CSV files for 2025-08.
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-08-03 00:00:00+07:00  2025-08-03T07:00:00+07:00             0.0
1  2025-08-03 00:00:00+07:00  2025-08-03T07:00:00+07:00             0.0
2  2025-08-03 00:00:00+07:00  2025-08-03T07:00:00+07:00             0.0
3  2025-08-03 00:00:00+07:00  2025-08-03T07:00:00+07:00             9.0
4  2025-08-03 00:00:00+07:00  2025-08-03T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime source_folder  \
0         575571.0               BKC007       2025-08-02       2025-08
1        1512928.0                  NaN       2025-08-02       2025-08
2        1512927.0                  NaN       2025-08-02       2025-08
3        1395256.0                  NaN       2025-08-02       2025-08
4        1395255.0                  NaN       2025-08-02       2025-08

                         source_file station_code  value
0  HII_daily_rainfall_2025-08-02.csv          NaN    NaN
1  HII_daily_rainfall_2025-08-02.csv          NaN    NaN
2  HII_daily_rainfall_2025-08-02.csv          NaN    NaN
3  HII_daily_rainfall_2025-08-02.csv          NaN    NaN
4  HII_daily_rainfall_2025-08-02.csv          NaN    NaN

In [56]:
dfs_09 = []
target_month09 = '2025-09'

for dirpath, dirnames, filenames in os.walk(root_directory):
    if target_month09 in dirpath:
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(dirpath, filename)
                try:
                    df_temp = pd.read_csv(file_path)
                    df_temp['source_folder'] = os.path.basename(dirpath)
                    df_temp['source_file'] = filename
                    dfs_09.append(df_temp)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

if dfs_09:
    final_df09 = pd.concat(dfs_09, ignore_index=True)
    print(f"Successfully concatenated {len(dfs_09)} CSV files for {target_month09}.")
    print(final_df09.head())
else:
    final_df09 = pd.DataFrame()
    print(f"No CSV files found for {target_month09} that match the criteria, or an error occurred.")

Successfully concatenated 32 CSV files for 2025-09.
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-09-24 00:00:00+07:00  2025-09-24T07:00:00+07:00             2.4
1  2025-09-24 00:00:00+07:00  2025-09-24T07:00:00+07:00             0.8
2  2025-09-24 00:00:00+07:00  2025-09-24T07:00:00+07:00            23.4
3  2025-09-24 00:00:00+07:00  2025-09-24T07:00:00+07:00             0.2
4  2025-09-24 00:00:00+07:00  2025-09-24T07:00:00+07:00             0.2

   tele_station_id tele_station_oldcode measure_datetime source_folder  \
0        1109572.0               ONE083       2025-09-23       2025-09
1            672.0                 WTBT       2025-09-23       2025-09
2            671.0               DIV002       2025-09-23       2025-09
3            854.0                 TSDO       2025-09-23       2025-09
4            611.0               DIV005       2025-09-23       2025-09

                         source_file station_code  value
0  HII_daily_rainfall_2025-09-23.csv          NaN    NaN
1  HII_daily_rainfall_2025-09-23.csv          NaN    NaN
2  HII_daily_rainfall_2025-09-23.csv          NaN    NaN
3  HII_daily_rainfall_2025-09-23.csv          NaN    NaN
4  HII_daily_rainfall_2025-09-23.csv          NaN    NaN

In [57]:
dfs_10 = []
target_month10 = '2025-10'

for dirpath, dirnames, filenames in os.walk(root_directory):
    if target_month10 in dirpath:
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(dirpath, filename)
                try:
                    df_temp = pd.read_csv(file_path)
                    df_temp['source_folder'] = os.path.basename(dirpath)
                    df_temp['source_file'] = filename
                    dfs_10.append(df_temp)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

if dfs_10:
    final_df10 = pd.concat(dfs_10, ignore_index=True)
    print(f"Successfully concatenated {len(dfs_10)} CSV files for {target_month10}.")
    print(final_df10.head())
else:
    final_df10 = pd.DataFrame()
    print(f"No CSV files found for {target_month10} that match the criteria, or an error occurred.")

Successfully concatenated 31 CSV files for 2025-10.
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-10-08 00:00:00+07:00  2025-10-07T07:00:00+07:00             0.0
1  2025-10-08 00:00:00+07:00  2025-10-07T07:00:00+07:00             0.0
2  2025-10-08 00:00:00+07:00  2025-10-07T07:00:00+07:00             0.0
3  2025-10-08 00:00:00+07:00  2025-10-07T07:00:00+07:00             0.2
4  2025-10-08 00:00:00+07:00  2025-10-07T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime source_folder  \
0              417               VLGE04       2025-10-07       2025-10
1              464               WAN002       2025-10-07       2025-10
2              898               VLGE42       2025-10-07       2025-10
3          1198626               TRD005       2025-10-07       2025-10
4              698                 WCBR       2025-10-07       2025-10

                         source_file
0  HII_daily_rainfall_2025-10-07.csv
1  HII_daily_rainfall_2025-10-07.csv
2  HII_daily_rainfall_2025-10-07.csv
3  HII_daily_rainfall_2025-10-07.csv
4  HII_daily_rainfall_2025-10-07.csv

In [58]:
dfs_11 = []
target_month11 = '2025-11'

for dirpath, dirnames, filenames in os.walk(root_directory):
    if target_month11 in dirpath:
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(dirpath, filename)
                try:
                    df_temp = pd.read_csv(file_path)
                    df_temp['source_folder'] = os.path.basename(dirpath)
                    df_temp['source_file'] = filename
                    dfs_11.append(df_temp)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

if dfs_11:
    final_df11 = pd.concat(dfs_11, ignore_index=True)
    print(f"Successfully concatenated {len(dfs_11)} CSV files for {target_month11}.")
    print(final_df11.head())
else:
    final_df11 = pd.DataFrame()
    print(f"No CSV files found for {target_month11} that match the criteria, or an error occurred.")

Successfully concatenated 30 CSV files for 2025-11.
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-11-08 00:00:00+07:00  2025-11-07T07:00:00+07:00             0.0
1  2025-11-08 00:00:00+07:00  2025-11-07T07:00:00+07:00            11.6
2  2025-11-08 00:00:00+07:00  2025-11-07T07:00:00+07:00            15.4
3  2025-11-08 00:00:00+07:00  2025-11-07T07:00:00+07:00            26.0
4  2025-11-08 00:00:00+07:00  2025-11-07T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime source_folder  \
0           455701               ONWR02       2025-11-07       2025-11
1          1109584               ONE095       2025-11-07       2025-11
2              618               SKG005       2025-11-07       2025-11
3              278                 TKPP       2025-11-07       2025-11
4          1109580               ONE091       2025-11-07       2025-11

                         source_file
0  HII_daily_rainfall_2025-11-07.csv
1  HII_daily_rainfall_2025-11-07.csv
2  HII_daily_rainfall_2025-11-07.csv
3  HII_daily_rainfall_2025-11-07.csv
4  HII_daily_rainfall_2025-11-07.csv

In [59]:
dfs_12 = []
target_month12 = '2025-12'

for dirpath, dirnames, filenames in os.walk(root_directory):
    if target_month12 in dirpath:
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(dirpath, filename)
                try:
                    df_temp = pd.read_csv(file_path)
                    df_temp['source_folder'] = os.path.basename(dirpath)
                    df_temp['source_file'] = filename
                    dfs_12.append(df_temp)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

if dfs_12:
    final_df12 = pd.concat(dfs_12, ignore_index=True)
    print(f"Successfully concatenated {len(dfs_12)} CSV files for {target_month12}.")
    print(final_df12.head())
else:
    final_df12 = pd.DataFrame()
    print(f"No CSV files found for {target_month12} that match the criteria, or an error occurred.")

Successfully concatenated 31 CSV files for 2025-12.
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0
1  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0
2  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0
3  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0
4  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime source_folder  \
0          1109576               ONE087       2025-12-02       2025-12
1              135               VLGE03       2025-12-02       2025-12
2              134               TRD004       2025-12-02       2025-12
3              114                 UTOG       2025-12-02       2025-12
4              103               TB0004       2025-12-02       2025-12

                         source_file
0  HII_daily_rainfall_2025-12-02.csv
1  HII_daily_rainfall_2025-12-02.csv
2  HII_daily_rainfall_2025-12-02.csv
3  HII_daily_rainfall_2025-12-02.csv
4  HII_daily_rainfall_2025-12-02.csv

##รวมทุกเดือน

In [60]:
all_months_df = pd.concat([
    final_df07,
    final_df08,
    final_df09,
    final_df10,
    final_df11,
    final_df12
], ignore_index=True)

print("Successfully concatenated all monthly DataFrames into all_months_df. First 5 rows:")
display(all_months_df.head())
print("\nShape of the combined DataFrame:")
print(all_months_df.shape)
print("\nColumns in the combined DataFrame:")
print(all_months_df.columns.tolist())

Successfully concatenated all monthly DataFrames into all_months_df. First 5 rows:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,source_folder,source_file,station_code,value
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277.0,BNAK,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN

Shape of the combined DataFrame:
(180700, 10)

Columns in the combined DataFrame:
['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value', 'tele_station_id', 'tele_station_oldcode', 'measure_datetime', 'source_folder', 'source_file', 'station_code', 'value']

In [61]:
all_months_df

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,source_folder,source_file,station_code,value
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277.0,BNAK,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09,2025-07,HII_daily_rainfall_2025-07-09.csv,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
180695,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,254.0,BJAN,2025-12-13,2025-12,HII_daily_rainfall_2025-12-13.csv,NaN,NaN
180696,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,308.0,WEI012,2025-12-13,2025-12,HII_daily_rainfall_2025-12-13.csv,NaN,NaN
180697,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,770.0,GLF003,2025-12-13,2025-12,HII_daily_rainfall_2025-12-13.csv,NaN,NaN
180698,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,1109588.0,ONE099,2025-12-13,2025-12,HII_daily_rainfall_2025-12-13.csv,NaN,NaN
180699,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,286.0,TSUD,2025-12-13,2025-12,HII_daily_rainfall_2025-12-13.csv,NaN,NaN

#อธิบายความหมายคอลัมของแต่ละไฟล์

**all_months_df**

| คอลัมน์                  | ความหมาย                                                                  |
| ------------------------ | ------------------------------------------------------------------------- |
| `rainfall_datetime`      | วัน–เวลา ที่เกิดฝน (เวลาจริงจากแหล่งข้อมูล)                               |
| `rainfall_datetime_calc` | วัน–เวลาที่ระบบคำนวณหรือปรับแล้ว (เช่น ปรับ timezone / aggregate)         |
| `rainfall_value`         | ปริมาณน้ำฝนที่วัดได้ (มักเป็นมิลลิเมตร)                                   |
| `tele_station_id`        | รหัสสถานีฝน (รหัสภายในระบบโทรมาตร)                                        |
| `tele_station_oldcode`   | รหัสสถานีแบบเดิม (ใช้เชื่อมข้อมูลเก่า)                                    |
| `measure_datetime`       | วัน–เวลาที่มีการวัดค่าฝน                                                  |
| `source_folder`          | ชื่อโฟลเดอร์ที่ไฟล์ข้อมูลอยู่ (เช่น เดือน/วัน)                            |
| `source_file`            | ชื่อไฟล์ต้นทางที่อ่านข้อมูลมา                                             |
| `station_code`           | รหัสสถานี (ใช้ระบุสถานีหลัก)                                              |
| `value`                  | ค่าฝนที่ใช้ในการวิเคราะห์ (มักซ้ำหรือผ่านการประมวลผลจาก `rainfall_value`) |

**stations**

| คอลัมน์ | ความหมาย                                  |
| ------- | ----------------------------------------- |
| `Node`  | รหัสสถานีที่ใช้งานได้ (station code หลัก) |
| `Lat`   | ละติจูดของสถานี                           |
| `Long`  | ลองจิจูดของสถานี                          |

#2.กรองข้อมูล

##ข้อมูลก่อนกรอง

In [73]:
stations.shape

(385, 3)

In [75]:
all_months_df.shape
all_months_df['station_code'].unique().shape

(1340,)

##หลังกรอง

In [71]:
filtered_df = all_months_df[
    all_months_df['station_code'].isin(stations['Node'])
]

In [72]:
filtered_df.shape
filtered_df['station_code'].unique()

array(['ACRU', 'BBHN', 'BBUA', 'BCNG', 'BDAR', 'BDGN', 'BDLH', 'BDMG',
       'BGRT', 'BHMN', 'BHUN', 'BJIG', 'BKDN', 'BKHL', 'BKK001', 'BKK008',
       'BKK015', 'BKK018', 'BKK019', 'BKUG', 'BKWN', 'BLAT', 'BLKO',
       'BLUG', 'BMDG', 'BMNK', 'BNAN', 'BNHG', 'BNHI', 'BNHO', 'BNKN',
       'BNKP', 'BNMK', 'BNPI', 'BNPU', 'BNTK', 'BOKA', 'BPIA', 'BPK004',
       'BPLA', 'BPPS', 'BRKM', 'BSBA', 'BSDE', 'BSMP', 'BSUM', 'BTHO',
       'BWKG', 'BYNU', 'CATK', 'CBUR', 'CCSS', 'CEHM', 'CGDO', 'CGMN',
       'CGSN', 'CHHA', 'CHI005', 'CHI011', 'CHI012', 'CHM002', 'CHM003',
       'CHM004', 'CHR003', 'CHR004', 'CHR005', 'CHUN', 'CLPK', 'CMSG',
       'CPKC', 'CPY003', 'CPY004', 'CPY009', 'CPY010', 'CPY012', 'CPY013',
       'CPY015', 'CPY017', 'CSMO', 'DITO', 'DIV001', 'DIV002', 'DIV003',
       'DIV004', 'DIV005', 'DKLG', 'DKTI', 'DMKH', 'DNCM', 'DSKT', 'DTAN',
       'HCTT', 'HKTG', 'HNKA', 'HNRE', 'HSYO', 'HTTM', 'HUYG', 'HYOD',
       'HYRT', 'JBLG', 'KABG', 'KAHN', 'KAKG', 'KANG', 'KAOP', 'KGKG',
       'KGLN', 'KHHM', 'KHPB', 'KKHA', 'KKPA', 'KKWF', 'KMSI', 'KNYM',
       'KOKN', 'KOLO', 'KON002', 'KON004', 'KON005', 'KOSB', 'KOSK',
       'KOSR', 'KPEM', 'KRKM', 'KRN002', 'KSOD', 'KSPS', 'KTKB', 'KTLE',
       'KWSI', 'LBI002', 'LEEE', 'LK13', 'LMPN', 'LMSK', 'LPLE', 'MCHI',
       'MCRM', 'MDTG', 'MECN', 'MEPK', 'MEWG', 'MKTR', 'MMMO', 'MMNY',
       'MRMT', 'MUN011', 'MUN014', 'NAKU', 'NAMN', 'NAN001', 'NAN006',
       'NAN010', 'NAN011', 'NAN012', 'NAN013', 'NAN014', 'NANI', 'NAPJ',
       'NGBA', 'NGCG', 'NGCH', 'NKMT', 'NKNN', 'NKO001', 'NKO002', 'NKOK',
       'NKSG', 'NKTI', 'NKYG', 'NMKH', 'NMKI', 'NMPR', 'NMPT', 'NNKO',
       'NOKK', 'NPCT', 'NPI001', 'NPNK', 'NPSD', 'NSRS', 'NTAN', 'NTNG',
       'NTST', 'NYK000', 'PAI002', 'PAII', 'PAS001', 'PAS002', 'PASG',
       'PDAM', 'PGKH', 'PHON', 'PHPS', 'PICI', 'PIN003', 'PIN004',
       'PIN005', 'PIN006', 'PLTL', 'PONG', 'PPAN', 'PPCT', 'PPRM', 'PPTC',
       'PRC003', 'PRGB', 'PSLI', 'PTLE', 'PTWY', 'PYMR', 'PYO001',
       'RAJ002', 'RAY001', 'RBPI', 'RGKG', 'RIKK', 'RNG001', 'RNGH',
       'SAY001', 'SAY002', 'SBT1', 'SENM', 'SISU', 'SITP', 'SKE001',
       'SKE002', 'SKE003', 'SKG002', 'SKG005', 'SKG007', 'SKKG', 'SKM005',
       'SLA002', 'SLBC', 'SMSU', 'SNGT', 'SNKO', 'SOKL', 'SPPT', 'SPWA',
       'SRKT', 'SSRG', 'STH004', 'STH005', 'STH011', 'STH014', 'STH016',
       'STH018', 'STH022', 'STH025', 'STH029', 'STH030', 'STU001', 'STWN',
       'SVI001', 'SVI002', 'SWAR', 'SWH1', 'SWKL', 'SWNG', 'SYTL', 'TAPE',
       'TEPT', 'TETN', 'TGLG', 'TGSK', 'THA001', 'THA003', 'THA006',
       'THA010', 'THA011', 'THCG', 'THNG', 'THNM', 'THTN', 'TKFA', 'TKNT',
       'TKRA', 'TLAN', 'TMLI', 'TNG001', 'TNG002', 'TOGO', 'TON001',
       'TON006', 'TPI001', 'TPI002', 'TPI004', 'TPI005', 'TPI007', 'TPPN',
       'TPTN', 'TPUR', 'TRD001', 'TRD002', 'TRON', 'TSLM', 'TSUD', 'TTKO',
       'TTLG', 'TTWY', 'VLGE01', 'VLGE14', 'VLGE27', 'VLGE29', 'VLGE31',
       'VLGE32', 'VLGE33', 'VLGE41', 'VLGE42', 'WAN001', 'WAN002', 'WBYN',
       'WCBR', 'WCHN', 'WCTK', 'WEI071', 'WGCI', 'WGKN', 'WGNA', 'WGTG',
       'WNKH', 'WNMI', 'WPAP', 'WRRS', 'WTBT', 'WTCH', 'WTLG', 'WTSG',
       'WWST', 'YGHM', 'YOM001', 'YOM003', 'YOM008', 'YOM009', 'YOM010',
       'YOM012', 'BDCP', 'CHPA', 'LNRG', 'NBON', 'PRC002', 'STH017',
       'TLPC', 'WSPN', 'NGNG', 'VLGE03'], dtype=object)

In [70]:
filtered_df.shape
filtered_df['station_code'].unique().shape

(349,)

In [74]:
set(all_months_df['station_code']) - set(stations['Node'])

{'AIT001',
 'AIT002',
 'AIT005',
 'AIT008',
 'AIT009',
 'AIT010',
 'AIT011',
 'ATG011',
 'ATG021',
 'ATG032',
 'ATG042',
 'ATG051',
 'ATG052',
 'ATG072',
 'ATG081',
 'ATG082',
 'ATG091',
 'ATG092',
 'ATG101',
 'ATG111',
 'ATG112',
 'ATG121',
 'ATG122',
 'ATG131',
 'ATG132',
 'ATG141',
 'ATG142',
 'ATG151',
 'ATG152',
 'ATG161',
 'ATG171',
 'ATG181',
 'ATG182',
 'BARI',
 'BDWN',
 'BGBO',
 'BGIM01',
 'BGYN',
 'BHPK',
 'BJAN',
 'BKC001',
 'BKC002',
 'BKC003',
 'BKC004',
 'BKC005',
 'BKC006',
 'BKC007',
 'BKC008',
 'BKHI',
 'BKK002',
 'BKK004',
 'BKK006',
 'BKK007',
 'BKK013',
 'BKK016',
 'BKK021',
 'BKNH',
 'BMKN',
 'BMOD',
 'BNAK',
 'BNKE',
 'BNPK',
 'BOP1',
 'BPK003',
 'BPUG',
 'BPUN',
 'BSCL',
 'BSP002',
 'BSVT',
 'BTCH',
 'BTGH',
 'BTHI',
 'BTUD',
 'BTUM',
 'BTWN',
 'BUGN',
 'BUKT',
 'CAN001',
 'CHAU01',
 'CHI001',
 'CHI003',
 'CHK001',
 'CHK002',
 'CHKG',
 'CHM005',
 'CHN001',
 'CHN005',
 'CHR001',
 'CHR002',
 'CHR007',
 'CHTG',
 'CIHO',
 'CKLG',
 'CMKK',
 'CMP001',
 'CNDN',
 'CPON',
 'CPY001',
 'CPY002',
 'CPY005',
 'CPY006',
 'CPY007',
 'CPY008',
 'CPY011',
 'CPY014',
 'CPY016',
 'DDSO',
 'DIWO',
 'DKMU',
 'DMH001',
 'DMH002',
 'DMH003',
 'DMH005',
 'DMH006',
 'DMH007',
 'DMH008',
 'DMH009',
 'DMH010',
 'DMH011',
 'DMH012',
 'DMH013',
 'DMH014',
 'DMH015',
 'DMH016',
 'DMH017',
 'DMH018',
 'DMH019',
 'DMH020',
 'DMS001',
 'DNP035',
 'DOCI',
 'FANG',
 'FOP001',
 'FOP002',
 'FOP007',
 'FOP008',
 'FOP009',
 'FOP010',
 'FOP011',
 'FOP013',
 'FOP014',
 'FOP015',
 'FOP016',
 'FOP018',
 'FOP019',
 'FOP020',
 'FOP021',
 'FOP022',
 'FOP024',
 'FOP025',
 'FOP026',
 'FOP027',
 'FOP028',
 'FOP029',
 'FOP030',
 'FOP032',
 'FOP033',
 'FOP034',
 'FOP035',
 'FOP038',
 'FOP039',
 'FOP040',
 'FOP041',
 'FOP042',
 'FOP044',
 'FOP045',
 'FOP046',
 'FOP047',
 'FOP048',
 'FOP049',
 'FOP050',
 'FOP052',
 'FOP053',
 'FOP054',
 'FOP055',
 'FOP056',
 'FOP057',
 'FOP058',
 'FOP059',
 'FOP060',
 'FOP061',
 'FOP062',
 'FOP063',
 'FOP065',
 'FOP066',
 'FOP067',
 'FOP068',
 'FOP069',
 'FOP070',
 'FOP071',
 'FOP072',
 'FROC01',
 'GOT001',
 'HDA001',
 'HDA002',
 'HDA003',
 'HDA004',
 'HDA005',
 'HDA006',
 'HDA007',
 'HDA008',
 'HDA009',
 'HDA010',
 'HDA011',
 'HDA012',
 'HII001',
 'HII002',
 'HIKT',
 'HJRN1',
 'HOTT',
 'HUKT',
 'INET01',
 'JNA001',
 'JNA002',
 'KGTP',
 'KHCP',
 'KHDM',
 'KHOG',
 'KIZ001',
 'KIZ003',
 'KKCN',
 'KMTK',
 'KNDG',
 'KOKO',
 'KON001',
 'KON003',
 'KPPT',
 'KRMT',
 'KRN001',
 'KRN004',
 'KSKP',
 'KSNG',
 'KTUM',
 'KUAM',
 'KUBR',
 'KUDN',
 'KWN001',
 'KWN003',
 'KYKT',
 'LAO001',
 'LAO002',
 'LAO003',
 'LAO004',
 'LAO009',
 'LBI001',
 'LDKS',
 'LGTI',
 'LHOK',
 'LKBU',
 'LMKO',
 'LNR1',
 'LNSK',
 'MDC001',
 'MDC005',
 'MITP01',
 'MKKB',
 'MNDM',
 'MOU001',
 'MOU002',
 'MOU003',
 'MOU005',
 'MOU006',
 'MOU007',
 'MOU008',
 'MOU009',
 'MOU010',
 'MOU011',
 'MOU012',
 'MOU013',
 'MOU014',
 'MOU015',
 'MOU016',
 'MOU017',
 'MOU018',
 'MOU019',
 'MOU020',
 'MOU021',
 'MOU023',
 'MOU024',
 'MOU025',
 'MOU026',
 'MOU027',
 'MOU028',
 'MOU029',
 'MOU030',
 'MOU031',
 'MOU032',
 'MOU033',
 'MOU034',
 'MOU035',
 'MOU036',
 'MOU037',
 'MOU038',
 'MOU040',
 'MOU041',
 'MOU042',
 'MOU043',
 'MOU044',
 'MOU045',
 'MOU046',
 'MOU047',
 'MOU048',
 'MOU050',
 'MOU051',
 'MOU052',
 'MOU053',
 'MOU054',
 'MOU055',
 'MOU056',
 'MOU057',
 'MOU059',
 'MOU060',
 'MOU061',
 'MOU062',
 'MOU063',
 'MOU064',
 'MOU065',
 'MOU066',
 'MOU067',
 'MOU068',
 'MOU069',
 'MOU071',
 'MOU072',
 'MOU073',
 'MOU074',
 'MOU075',
 'MOU076',
 'MOU078',
 'MOU079',
 'MOU080',
 'MOU081',
 'MOU083',
 'MOU084',
 'MOU085',
 'MOU086',
 'MOU088',
 'MOU090',
 'MOU091',
 'MOU092',
 'MOU093',
 'MOU096',
 'MOU097',
 'MOU098',
 'MOU099',
 'MOU100',
 'MOU102',
 'MOU103',
 'MOU104',
 'MOU106',
 'MOU107',
 'MOU108',
 'MOU110',
 'MOU111',
 'MOU112',
 'MOU114',
 'MOU115',
 'MOU117',
 'MOU118',
 'MOU119',
 'MOU121',
 'MOU122',
 'MOU123',
 'MOU124',
 'MOU128',
 'MOU131',
 'MOU132',
 'MOU133',
 'MOU134',
 'MOU135',
 'MOU136',
 'MOU137',
 'MOU139',
 'MOU140',
 'MOU141',
 'MOU142',
 'MOU143',
 'MOU146',
 'MOU147',
 'MOU148',
 'MOU149',
 'MOU152',
 'MOU153',
 'MOU155',
 'MOU156',
 'MOU167',
 'MOU171',
 'MOU172',
 'MOU174',
 'MOU175',
 'MOU176',
 'MOU177',
 'MOU178',
 'MOU180',
 'MOU181',
 'MOU182',
 'MOU183',
 'MOU184',
 'MOU189',
 'MOU190',
 'MOU191',
 'MOU192',
 'MOU193',
 'MOU194',
 'MOU195',
 'MOU196',
 'MOU197',
 'MOU198',
 'MOU199',
 'MOU201',
 'MOU202',
 'MOU204',
 'MOU219',
 'MOU226',
 'MOU229',
 'MOU231',
 'MOU232',
 'MOU233',
 'MOU235',
 'MOU237',
 'MOU241',
 'MOU246',
 'MOU251',
 'MOU252',
 'MOU256',
 'MOU257',
 'MOU258',
 'MOU259',
 'MOU260',
 'MOU263',
 'MOU268',
 'MOU269',
 'MOU271',
 'MOU272',
 'MOU273',
 'MOU274',
 'MOU276',
 'MOU278',
 'MOU282',
 'MOU283',
 'MOU284',
 'MOU285',
 'MOU286',
 'MOU288',
 'MOU289',
 'MOU290',
 'MOU291',
 'MOU292',
 'MOU293',
 'MOU294',
 'MOU295',
 'MOU296',
 'MOU297',
 'MOU299',
 'MOU300',
 'MOU301',
 'MOU302',
 'MOU303',
 'MOU304',
 'MOU305',
 'MOU306',
 'MOU307',
 'MOU308',
 'MOU309',
 'MOU310',
 'MOU311',
 'MOU312',
 'MOU313',
 'MOU314',
 'MOU315',
 'MOU316',
 'MOU318',
 'MOU319',
 'MOU320',
 'MOU321',
 'MOU322',
 'MOU323',
 'MOU324',
 'MOU325',
 'MOU327',
 'MOU328',
 'MOU329',
 'MOU330',
 'MOU331',
 'MOU333',
 'MOU335',
 'MOU336',
 'MOU337',
 'MOU338',
 'MOU339',
 'MOU340',
 'MOU341',
 'MOU342',
 'MOU343',
 'MOU346',
 'MOU347',
 'MOU348',
 'MOU349',
 'MOU350',
 'MOU351',
 'MOU352',
 'MOU353',
 'MOU355',
 'MOU356',
 'MOU357',
 'MOU358',
 'MOU359',
 'MOU360',
 'MOU362',
 'MOU363',
 'MOU365',
 'MOU366',
 'MOU368',
 'MOU369',
 'MOU370',
 'MOU371',
 'MOU372',
 'MOU373',
 'MOU374',
 'MOU375',
 'MOU376',
 'MOU378',
 'MOU379',
 'MOU380',
 'MOU383',
 'MOU384',
 'MOU385',
 'MOU386',
 'MOU388',
 'MOU389',
 'MOU390',
 'MOU391',
 'MOU392',
 'MOU395',
 'MOU396',
 'MOU397',
 'MOU398',
 'MOU399',
 'MOU400',
 'MOU401',
 'MOU402',
 'MOU403',
 'MOU404',
 'MOU405',
 'MOU406',
 'MOU407',
 'MOU408',
 'MOU409',
 'MOU410',
 'MOU411',
 'MOU412',
 'MOU413',
 'MOU415',
 'MOU416',
 'MOU418',
 'MOU419',
 'MOU424',
 'MOU426',
 'MOU427',
 'MOU428',
 'MOU429',
 'MOU430',
 'MOU431',
 'MOU435',
 'MOU441',
 'MOU454',
 'MOU460',
 'MOU461',
 'MOU462',
 'MOU464',
 'MOU465',
 'MOU467',
 'MOU469',
 'MOU471',
 'MOU472',
 'MOU475',
 'MOU476',
 'MOU477',
 'MOU478',
 'MOU479',
 'MOU481',
 'MOU482',
 'MOU483',
 'MOU484',
 'MOU485',
 'MOU486',
 'MOU487',
 'MOU490',
 'MOU491',
 'MOU492',
 'MOU493',
 'MOU494',
 'MOU495',
 'MOU496',
 'MOU497',
 'MOU499',
 'MOU500',
 'MOU501',
 'MOU502',
 'MOU505',
 'MOU506',
 'MOU507',
 'MOU509',
 'MOU510',
 'MPBR',
 'MSRM',
 'MUN002',
 'MUN003',
 'MUN005',
 'MUN009',
 'MUN010',
 'MUN012',
 'MWOG',
 'MYA001',
 'MYA002',
 'MYA003',
 'MYA004',
 'NAN003',
 'NAN004',
 'NAN005',
 'NAN007',
 'NAN008',
 'NAN009',
 'NAN015',
 'NAN016',
 'NANP',
 'NANT',
 'NASG',
 'NBLK',
 'NGSC',
 'NIKS',
 'NKO003',
 'NKO004',
 'NKTP',
 'NMKO',
 'NMNO',
 'NMUB',
 'NNDG',
 'NOKG',
 'NOKW',
 'NONA',
 'NOPU',
 'NSNO',
 'NTTI',
 'NWSO',
 'NYK001',
 'NYK008',
 'NYK014',
 'OMKI',
 'ONE001',
 'ONE002',
 'ONE003',
 'ONE004',
 'ONE005',
 'ONE006',
 'ONE007',
 'ONE008',
 'ONE009',
 'ONE011',
 'ONE012',
 'ONE013',
 'ONE017',
 'ONE018',
 'ONE020',
 'ONE021',
 'ONE022',
 'ONE023',
 'ONE024',
 'ONE025',
 'ONE028',
 'ONE029',
 'ONE030',
 'ONE033',
 'ONE035',
 'ONE036',
 'ONE037',
 'ONE039',
 'ONE040',
 'ONE041',
 'ONE042',
 'ONE044',
 'ONE045',
 'ONE046',
 'ONE047',
 'ONE048',
 'ONE049',
 'ONE051',
 'ONE053',
 'ONE054',
 'ONE055',
 'ONE056',
 'ONE057',
 'ONE059',
 'ONE061',
 'ONE062',
 'ONE063',
 'ONE065',
 'ONE067',
 'ONE068',
 'ONE069',
 'ONE070',
 'ONE071',
 'ONE072',
 'ONE073',
 'ONE074',
 'ONE075',
 'ONE076',
 'ONE079',
 'ONE080',
 'ONE081',
 'ONE082',
 'ONE083',
 'ONE086',
 'ONE088',
 'ONE089',
 'ONE090',
 'ONE091',
 'ONE092',
 'ONE094',
 'ONE095',
 'ONE096',
 'ONE097',
 'ONE098',
 'ONE100',
 'ONE101',
 'ONE102',
 'ONE103',
 'ONE104',
 'ONE106',
 'ONE107',
 'ONE108',
 'ONE109',
 'ONE110',
 'PADT',
 'PALU',
 'PANC',
 'PAS009',
 'PAS010',
 'PAT002',
 'PATO01',
 'PCH002',
 'PCH003',
 'PHKD',
 'PIN001',
 'PIN002',
 'PIN007',
 'PIN008',
 'PIN009',
 'PIN010',
 'PIN011',
 'PKH1',
 'PKTI',
 'PLG001',
 'PMPA',
 'PNCR',
 'PNRN',
 'POCE',
 'POCG',
 'PRC001',
 'PRC004',
 'PRC005',
 'PRN002',
 'PRST',
 'PRUK',
 'PTT001',
 'PTT002',
 'PTT003',
 'PTT004',
 'PTYS',
 'PVEE',
 'PWA003',
 'PWA005',
 'PYO002',
 'PYO003',
 'PYO004',
 'RAY004',
 'RES001',
 'RES002',
 'RES003',
 'RES004',
 'RES005',
 'RES006',
 'RES007',
 'RES008',
 'RES009',
 'RES010',
 'RES011',
 'RES012',
 'RES013',
 'RES014',
 'RES015',
 'RES016',
 'RES017',
 'RES018',
 'RES019',
 'RES020',
 'RES021',
 'RES022',
 'RES023',
 'RES024',
 'RFBK',
 'RMMI',
 'RSW001',
 'RSW002',
 'RSW003',
 'SACS',
 'SBRS',
 'SDO001',
 'SDO002',
 'SDO003',
 'SGMN',
 'SKBI',
 'SKG003',
 'SKG004',
 'SKG008',
 'SKN002',
 'SKN003',
 'SKPG',
 'SLA001',
 'SLA003',
 'SLA005',
 'SLA007',
 'SNSI',
 'STH001',
 'STH002',
 'STH006',
 'STH007',
 'STH008',
 'STH010',
 'STH012',
 'STH013',
 'STH015',
 'STH020',
 'STH021',
 'STH023',
 'STH024',
 'STH026',
 'STH027',
 'STU002',
 'STU003',
 'STU004',
 'SWR002',
 'SWR004',
 'SWR005',
 'SWR006',
 'SWR007',
 'SWR010',
 'SWR011',
 'SWR015',
 'SWR016',
 'SWR018',
 'SWR019',
 'SWR020',
 'SWR021',
 'SWR022',
 'SWR023',
 'SWR024',
 'SWR025',
 'SWR026',
 'SWR027',
 'SWR029',
 'SWR030',
 'SWR032',
 'SWR033',
 'SWR034',
 'SWR035',
 'SWR036',
 'SWR038',
 'SYKP',
 'TADE01',
 'TAKI',
 'TAKL',
 'TANA',
 'TB0001',
 'TB0004',
 'TB0005',
 'TB0006',
 'TB0007',
 'TBR011',
 'TBR012',
 'TBR013',
 'TBR014',
 'TBR015',
 'TBR016',
 'TBR017',
 'TBR019',
 'TBR022',
 'TBW008',
 'TBW009',
 'TBW014',
 'TBW017',
 'TBW019',
 'TBW022',
 'TBW023',
 'TBW024',
 'TBW025',
 'TBW026',
 'TBW027',
 'TBW029',
 'TBW030',
 'TBW032',
 'TBW033',
 'TBW035',
 'TCP002',
 'TCP003',
 'TCP004',
 'TCP005',
 'TCP006',
 'TCP007',
 'TCP008',
 'TCP009',
 'TCP011',
 'TCP012',
 'TCP013',
 'THA005',
 'THA008',
 'THA009',
 'THAT',
 'TLMU',
 'TNG003',
 'TNG004',
 'TNG005',
 'TNG006',
 'TON003',
 'TON004',
 'TPAE',
 'TPI003',
 'TPKO',
 'TRD003',
 'TRD004',
 'TRD005',
 'TRD007',
 'TSDO',
 'UPCT',
 'UTOG',
 'VLGE02',
 'VLGE04',
 'VLGE06',
 'VLGE08',
 'VLGE11',
 'VLGE12',
 'VLGE13',
 'VLGE15',
 'VLGE16',
 'VLGE17',
 'VLGE19',
 'VLGE20',
 'VLGE21',
 'VLGE25',
 'VLGE30',
 'VLGE35',
 'VLGE36',
 'VLGE43',
 'VLGE44',
 'VLGE45',
 'VLGE46',
 'VLGE47',
 'VLGE49',
 'VLGE50',
 'WAN003',
 'WAN004',
 'WEI011',
 'WEI012',
 'WEI041',
 'WEI052',
 'WEI061',
 'WEI062',
 'WEI072',
 'WEI092',
 'WEI101',
 'WEI112',
 'WEI122',
 'WEI132',
 'WEI141',
 'WEI142',
 'WEI151',
 'WGPO',
 'WGRY',
 'WGSA',
 'WGYG',
 'WSPR',
 'YBKM',
 'YKPC',
 'YOM004',
 'YOM005',
 'YOM006',
 'YOM007',
 'YOM013',
 'YOM014',
 'YOM015',
 'YOM016',
 nan}

##3.ข้อมูลสูญหาย

prompt :
ระบุข้อมูลสูญหาย(record ที่หายไป) ของแต่ละสถานี แสดงจำนวนและสัดส่วน ของไฟล์filtered_df (ข้อมูลสูญหาย ในที่นี้หมายถึง record ที่ไม่มีในไฟล์เลย ไม่ใช่ค่า NULL หรือ NaN)

In [121]:
import numpy as np

# Ensure all_months_df's measure_datetime is converted first to get the full date range
all_months_df['measure_datetime'] = pd.to_datetime(all_months_df['measure_datetime'], format='mixed', errors='coerce')

# Drop NaT values from all_months_df's measure_datetime temporarily to find global min/max
valid_measure_dates = all_months_df['measure_datetime'].dropna()
min_date = valid_measure_dates.min()
max_date = valid_measure_dates.max()

# Create filtered_df based on stations and the now-converted all_months_df
filtered_df = all_months_df[all_months_df['station_code'].isin(stations['Node'])].copy()

# The measure_datetime in filtered_df should already be datetime type, but ensure no NaTs exist for downstream calculations
filtered_df.dropna(subset=['measure_datetime'], inplace=True)

date_range = pd.date_range(start=min_date, end=max_date)
unique_stations = filtered_df['station_code'].unique()

expected_records_df = pd.DataFrame({
    'measure_datetime': np.tile(date_range, len(unique_stations)),
    'station_code': np.repeat(unique_stations, len(date_range))
})

print(f"Minimum date: {min_date}")
print(f"Maximum date: {max_date}")
print(f"Number of unique stations: {len(unique_stations)}")
print(f"Expected records DataFrame shape: {expected_records_df.shape}")
display(expected_records_df.head())

Minimum date: 2025-07-01 00:00:00
Maximum date: 2025-12-31 00:00:00
Number of unique stations: 349
Expected records DataFrame shape: (64216, 2)

  measure_datetime station_code
0       2025-07-01         ACRU
1       2025-07-02         ACRU
2       2025-07-03         ACRU
3       2025-07-04         ACRU
4       2025-07-05         ACRU

In [89]:
import numpy as np

filtered_df['measure_datetime'] = pd.to_datetime(filtered_df['measure_datetime'], format='mixed', errors='coerce')

# Drop rows where measure_datetime could not be parsed (NaT values)
filtered_df.dropna(subset=['measure_datetime'], inplace=True)

min_date = filtered_df['measure_datetime'].min()
max_date = filtered_df['measure_datetime'].max()
date_range = pd.date_range(start=min_date, end=max_date)
unique_stations = filtered_df['station_code'].unique()

expected_records_df = pd.DataFrame({
    'measure_datetime': np.tile(date_range, len(unique_stations)),
    'station_code': np.repeat(unique_stations, len(date_range))
})

print(f"Minimum date: {min_date}")
print(f"Maximum date: {max_date}")
print(f"Number of unique stations: {len(unique_stations)}")
print(f"Expected records DataFrame shape: {expected_records_df.shape}")
display(expected_records_df.head())

Minimum date: 2025-08-31 00:00:00
Maximum date: 2025-09-02 00:00:00
Number of unique stations: 349
Expected records DataFrame shape: (1047, 2)

  measure_datetime station_code
0       2025-08-31         ACRU
1       2025-09-01         ACRU
2       2025-09-02         ACRU
3       2025-08-31         BBHN
4       2025-09-01         BBHN

In [91]:
filtered_df = all_months_df[all_months_df['station_code'].isin(stations['Node'])].copy()

In [134]:
import numpy as np
import pandas as pd

# แปลงเวลาเป็น datetime
filtered_df['measure_datetime'] = pd.to_datetime(
    filtered_df['measure_datetime'],
    format='mixed',
    errors='coerce'
)

# ลบแถวที่ไม่มีเวลา
filtered_df = filtered_df.dropna(subset=['measure_datetime'])

# ---------- 🔴 แก้ตรงนี้ ----------
start_date = pd.to_datetime('2025-07-01')
end_date   = pd.to_datetime('2025-12-31')

date_range = pd.date_range(
    start=start_date,
    end=end_date,
    freq='D'
)
# ----------------------------------

unique_stations = filtered_df['station_code'].unique()

expected_records_df = pd.DataFrame({
    'measure_datetime': np.tile(date_range, len(unique_stations)),
    'station_code': np.repeat(unique_stations, len(date_range))
})

print(f"Start date (forced): {start_date}")
print(f"End date (forced): {end_date}")
print(f"Number of unique stations: {len(unique_stations)}")
print(f"Expected records DataFrame shape: {expected_records_df.shape}")

display(expected_records_df.head())

Start date (forced): 2025-07-01 00:00:00
End date (forced): 2025-12-31 00:00:00
Number of unique stations: 349
Expected records DataFrame shape: (64216, 2)

  measure_datetime station_code
0       2025-07-01         ACRU
1       2025-07-02         ACRU
2       2025-07-03         ACRU
3       2025-07-04         ACRU
4       2025-07-05         ACRU

In [135]:
merged_df = pd.merge(
    expected_records_df,
    filtered_df[['measure_datetime', 'station_code', 'rainfall_value', 'value']],
    on=['measure_datetime', 'station_code'],
    how='left'
)

print("Merged DataFrame head:")
display(merged_df.head())
print("Merged DataFrame shape:", merged_df.shape)

Merged DataFrame head:

  measure_datetime station_code  rainfall_value  value
0       2025-07-01         ACRU             NaN    NaN
1       2025-07-02         ACRU             NaN    NaN
2       2025-07-03         ACRU             NaN    NaN
3       2025-07-04         ACRU             NaN    NaN
4       2025-07-05         ACRU             NaN    NaN

Merged DataFrame shape: (64216, 4)

In [142]:
missing_records_count = merged_df[merged_df['value'].isna()].groupby('station_code').size().reset_index(name='missing_records')
total_records_count = merged_df.groupby('station_code').size().reset_index(name='total_records')

# Combine the counts
missing_summary = pd.merge(
    total_records_count,
    missing_records_count,
    on='station_code',
    how='left'
).fillna(0) # Fill NaN in 'missing_records' with 0 for stations with no missing data

# Calculate proportion of missing records
missing_summary['missing_proportion'] = (missing_summary['missing_records'] / missing_summary['total_records']) * 100

print("Summary of missing records per station:")
display(missing_summary.head())
print("\nStations with the highest proportion of missing records:")
display(missing_summary.sort_values(by='missing_proportion', ascending=False).head())

Summary of missing records per station:

  station_code  total_records  missing_records  missing_proportion
0         ACRU            184              181           98.369565
1         BBHN            184              181           98.369565
2         BBUA            184              181           98.369565
3         BCNG            184              181           98.369565
4         BDAR            184              181           98.369565

Stations with the highest proportion of missing records:

    station_code  total_records  missing_records  missing_proportion
147         MMMO            184              183           99.456522
316       VLGE31            184              183           99.456522
312       VLGE03            184              183           99.456522
163         NBON            184              183           99.456522
138         LNRG            184              183           99.456522

In [143]:
missing_summary[['station_code', 'missing_records']] \
    .sort_values(by='missing_records', ascending=False)

    station_code  missing_records
147         MMMO              183
316       VLGE31              183
312       VLGE03              183
163         NBON              183
138         LNRG              183
..           ...              ...
111         KHPB              181
110         KHHM              181
109         KGLN              181
108         KGKG              181
118         KOLO              181

[349 rows x 2 columns]

In [144]:
total_missing_records = missing_summary['missing_records'].sum()
print(f"Total missing records across all stations: {total_missing_records}")

Total missing records across all stations: 63193

In [145]:
stations_with_missing = missing_summary[missing_summary['missing_records'] > 0]
display(stations_with_missing)

    station_code  total_records  missing_records  missing_proportion
0           ACRU            184              181           98.369565
1           BBHN            184              181           98.369565
2           BBUA            184              181           98.369565
3           BCNG            184              181           98.369565
4           BDAR            184              181           98.369565
..           ...            ...              ...                 ...
344       YOM003            184              181           98.369565
345       YOM008            184              181           98.369565
346       YOM009            184              181           98.369565
347       YOM010            184              181           98.369565
348       YOM012            184              181           98.369565

[349 rows x 4 columns]

In [146]:
missing_detail = merged_df[merged_df['value'].isna()] \
    .sort_values(['station_code', 'measure_datetime'])

display(missing_detail[['station_code', 'measure_datetime']])

      station_code measure_datetime
0             ACRU       2025-07-01
1             ACRU       2025-07-02
2             ACRU       2025-07-03
3             ACRU       2025-07-04
4             ACRU       2025-07-05
...            ...              ...
62371       YOM012       2025-12-27
62372       YOM012       2025-12-28
62373       YOM012       2025-12-29
62374       YOM012       2025-12-30
62375       YOM012       2025-12-31

[63193 rows x 2 columns]

##4.คัดสถานีที่มีข้อมูลสูญหาย >=20%ออก

> คัดสถานีที่มีข้อมูลสูญหาย ≥ 20% (สถานีที่ถูกตัดออก)

In [147]:
removed_stations = missing_summary[
    missing_summary['missing_proportion'] >= 20
][['station_code', 'missing_proportion', 'missing_records']]

In [148]:
print("Stations removed (missing ≥ 20%):")
display(removed_stations.sort_values(by='missing_proportion', ascending=False))

Stations removed (missing ≥ 20%):

    station_code  missing_proportion  missing_records
147         MMMO           99.456522              183
316       VLGE31           99.456522              183
312       VLGE03           99.456522              183
163         NBON           99.456522              183
138         LNRG           99.456522              183
..           ...                 ...              ...
111         KHPB           98.369565              181
110         KHHM           98.369565              181
109         KGLN           98.369565              181
108         KGKG           98.369565              181
118         KOLO           98.369565              181

[349 rows x 3 columns]

> นับจำนวนสถานีที่ถูกคัดออก

In [149]:
num_removed = removed_stations['station_code'].nunique()
print(f"Number of removed stations: {num_removed}")

Number of removed stations: 349

> คัดเฉพาะสถานีที่ “ข้อมูลผ่านเกณฑ์” (< 20%)

In [150]:
remaining_stations = missing_summary[
    missing_summary['missing_proportion'] < 20
]

> นับจำนวนสถานีที่เหลือ

In [151]:
num_remaining = remaining_stations['station_code'].nunique()
print(f"Number of remaining stations: {num_remaining}")

Number of remaining stations: 0

> กรองข้อมูลจริง (filtered_df) ให้เหลือเฉพาะสถานีที่ผ่านเกณฑ์

In [152]:
filtered_df_clean = filtered_df[
    filtered_df['station_code'].isin(remaining_stations['station_code'])
].copy()

In [153]:
print("Summary after filtering stations by missing data threshold (20%)")
print(f"- Total stations before filtering: {missing_summary['station_code'].nunique()}")
print(f"- Stations removed (≥20% missing): {num_removed}")
print(f"- Stations remaining (<20% missing): {num_remaining}")

Summary after filtering stations by missing data threshold (20%)
- Total stations before filtering: 349
- Stations removed (≥20% missing): 349
- Stations remaining (<20% missing): 0

## 5.เติมข้อมูล

> เพิ่ม Day of Year (DOY)

In [154]:
merged_df['dayofyear'] = merged_df['measure_datetime'].dt.dayofyear

> คำนวณ Median จาก historical data (แยกตามสถานี + DOY)

In [155]:
median_doy_station = (
    merged_df
    .dropna(subset=['value'])
    .groupby(['station_code', 'dayofyear'])['value']
    .median()
    .reset_index()
    .rename(columns={'value': 'median_value'})
)

> นำค่า Median มา merge กลับ

In [156]:
merged_df = pd.merge(
    merged_df,
    median_doy_station,
    on=['station_code', 'dayofyear'],
    how='left'
)

> เติมข้อมูลที่สูญหายด้วย Median

In [157]:
merged_df['value_filled'] = merged_df['value'].fillna(merged_df['median_value'])

> ตรวจสอบว่ายังมี record หายอีกหรือไม่

In [158]:
remaining_missing = merged_df['value_filled'].isna().sum()
print(f"Remaining missing records after imputation: {remaining_missing}")

Remaining missing records after imputation: 63193

> กรณีเหลือ NaN
เติมด้วย Median รายสถานี

In [159]:
station_median = (
    merged_df
    .groupby('station_code')['value']
    .median()
)

merged_df['value_filled'] = merged_df['value_filled'].fillna(
    merged_df['station_code'].map(station_median)
)

In [160]:
print("Remaining missing after fallback:",
      merged_df['value_filled'].isna().sum())

Remaining missing after fallback: 0

In [161]:
check_missing_records = merged_df['value_filled'].isna().any()
print("Any missing records left?", check_missing_records)

Any missing records left? False

#6.เหตุใดจึงเลือกใช้ Median แทน Mean

ในการเติมข้อมูลที่สูญหายในงานนี้ เลือกใช้ค่า Median แทนค่า Mean เนื่องจากลักษณะของข้อมูลปริมาณน้ำฝนมีการกระจายที่ไม่สม่ำเสมอ และมักพบค่าที่สูงผิดปกติในบางช่วงเวลา เช่น วันที่เกิดฝนตกหนัก ซึ่งค่าลักษณะนี้สามารถส่งผลกระทบต่อค่าเฉลี่ยได้โดยตรง หากใช้ค่า Mean ค่าที่นำมาเติมอาจสูงหรือต่ำเกินความเป็นจริง และไม่สะท้อนค่าปกติของข้อมูลในช่วงเวลานั้น

ค่า Median เป็นค่ากลางของข้อมูลและมีความทนทานต่อค่าผิดปกติมากกว่า จึงเหมาะสำหรับใช้แทนค่าที่หายไป เพราะช่วยลดอิทธิพลของค่าที่สูงหรือต่ำเกินไป นอกจากนี้ การคำนวณค่า Median จากข้อมูลย้อนหลังโดยอ้างอิงตามวันของปี (Day of Year) และแยกตามสถานี ยังช่วยรักษาลักษณะการเปลี่ยนแปลงตามฤดูกาลของข้อมูล และทำให้ค่าที่เติมมีความสอดคล้องกับพฤติกรรมของข้อมูลในพื้นที่เดียวกัน

การเลือกใช้ Median แทน Mean จึงช่วยให้ข้อมูลหลังการเติมมีความสมเหตุสมผลมากขึ้น ลดการบิดเบือนของข้อมูล และลดผลกระทบต่อการวิเคราะห์ในขั้นตอนถัดไป เช่น การวิเคราะห์แนวโน้มหรือการสร้างแบบจำลอง ทำให้ผลการวิเคราะห์มีความน่าเชื่อถือและสะท้อนสภาพข้อมูลจริงได้ดียิ่งขึ้น

#7.ปริมาณน้ำฝนรายเดือน

In [162]:
merged_df['measure_datetime'] = pd.to_datetime(
    merged_df['measure_datetime'],
    errors='coerce'
)

merged_df['year'] = merged_df['measure_datetime'].dt.year
merged_df['month'] = merged_df['measure_datetime'].dt.month

In [163]:
monthly_rain = (
    merged_df
    .groupby(['station_code', 'year', 'month'])['value_filled']
    .sum()
    .reset_index()
)

In [164]:
monthly_rain = monthly_rain.rename(columns={
    'station_code': 'Node',
    'value_filled': 'rain'
})

In [175]:
monthly_rain['rain'] = monthly_rain['rain'].round(1) # ปัดทศนิยมให้เหมือนตัวอย่าง
monthly_rain = monthly_rain.sort_values(by=['Node', 'year', 'month']).reset_index(drop=True)

# Reorder columns as requested
monthly_rain = monthly_rain[['Node', 'rain', 'month', 'year']]

print("ผลรวมปริมาณน้ำฝนรายเดือน (ทุกสถานีที่ผ่านเกณฑ์) พร้อมจัดเรียงคอลัมน์:")
display(monthly_rain.head(20))

ผลรวมปริมาณน้ำฝนรายเดือน (ทุกสถานีที่ผ่านเกณฑ์) พร้อมจัดเรียงคอลัมน์:

    Node    rain  month  year
0   ACRU     6.2      7  2025
1   ACRU     6.2      8  2025
2   ACRU    21.4      9  2025
3   ACRU     6.2     10  2025
4   ACRU     6.0     11  2025
5   ACRU     6.2     12  2025
6   BBHN  1884.8      7  2025
7   BBHN  1928.8      8  2025
8   BBHN  1775.4      9  2025
9   BBHN  1884.8     10  2025
10  BBHN  1824.0     11  2025
11  BBHN  1884.8     12  2025
12  BBUA    24.8      7  2025
13  BBUA    24.8      8  2025
14  BBUA    24.2      9  2025
15  BBUA    24.8     10  2025
16  BBUA    24.0     11  2025
17  BBUA    24.8     12  2025
18  BCNG   179.8      7  2025
19  BCNG   186.6      8  2025

In [176]:
from google.colab import files
files.download('monthly_rain.csv')